### ISSUE TITLE
[question] why remove query parameters from the req object?

### ISSUE THREAD

**Issue by Zertz** [florianholzapfel/express-restify-mongoose#103]
While I understand the purpose of the `cleanQuery` middleware, is there a particular reason to remove query parameters from the req object?

Simply removing `delete req.query[key];` breaks the tests although I don't understand why just yet.

In some cases, it would be convenient to retain access to this data.

**Comment by Zertz** [comment]
Aaaand fixed in #104

**Comment by florianholzapfel** [comment]
thank you!
