### ISSUE TITLE
More control over the path naming

### ISSUE THREAD

**Issue by bendpx** [florianholzapfel/express-restify-mongoose#105]
I have a model: User, I'm using express-restify-mongoose to serve it in my CRUD service. 

If I use the default the result is:
http://localhost:8080/api/v1/User (as a prefix)

What I want to achieve is to create a router to the model User and have a full control over the path:

var User = require('mongoose').model('User');
var restify = require('express-restify-mongoose');

module.exports = function (server) {
    restify.serve(router, User, {
        prefix: '',
        version: '',
        useModelName: false //what is missing
    });
    server.use('/user', router);
};
 
Then the api will be served on http://localhost:8080/user (as a prefix). Possible?

**Comment by florianholzapfel** [comment]
This is already possible, but it is not very obvious: use would need to additionally switch off pluralising and set the name option to ```:id```.

based on the invoicing example it would then look like this:
```
var router = express.Router();
restify.serve(router, CustomerModel, {
	prefix: '',
	version: '',
	name: ':id',
	plural: false
});
app.use('/customer', router);
```

**Comment by bendpx** [comment]
It worked, thanks you! amazing module, very usaful
