### ISSUE TITLE
Update Mongoose version

### ISSUE THREAD

**Issue by GaryTowers** [florianholzapfel/express-restify-mongoose#108]
Mongoose 4.0 got released and introduced many improvements [see release notes](https://github.com/Automattic/mongoose/wiki/4.0-Release-Notes) are there any plans to update express-restify-mongoose to take advantage of this?

**Comment by Zertz** [comment]
There are a few things that need to be looked at and tested first. I'm going to be upgrading a project of mine which uses express-restify-mongoose to 4.0 next week so I'll do some testing and submit changes if necessary.

**Comment by Zertz** [comment]
Turns out there are quite a few breaking changes, I'm going through the [notes](https://github.com/Automattic/mongoose/wiki/4.0-Release-Notes) at the moment. At least a few (if not most) are due to new defaults, I'll work on them and start pushing PR's tomorrow hopefully.

**Comment by Zertz** [comment]
See PR #114
