### ISSUE TITLE
updating an object with populated subfields 

### ISSUE THREAD

**Issue by ehmicky** [florianholzapfel/express-restify-mongoose#109]
If `GET /api/v1/resources/ID` returns:

    {  _id: ID, a: { b: ID2 } }

and `GET /api/v1/resources/ID?populate=a.b` returns:

    {  _id: ID, a: { b: { _id: ID2, c: "example" } } }

If I `PUT /api/v1/resources/ID` with the previously returned object as the request body, I get a `CastError` from Mongoose.

The reason is: updating populated fields works with `express-restify-mongoose`, providing they are at the root of the object, thanks to the following piece of code:

        for (var key in req.body) {
            var path = model.schema.path(key);
            if (typeof path === 'undefined') {
                continue;
            }

            if (path.caster !== undefined) {
                if (path.caster.instance === 'ObjectID') {
                    if (_.isArray(req.body[key])) {
                        for (var j = 0; j < req.body[key].length; ++j) {
                            if (typeof req.body[key][j] === 'object') {
                                req.body[key][j] = req.body[key][j]._id;
                            }
                        }
                    } else if ((typeof req.body[key] === 'object') &&
                        (req.body[key] !== null)) {
                        req.body[key] = req.body[key]._id;
                    }
                }
            } else if ((path.instance === 'ObjectID') &&
                (typeof req.body[key] === 'object') &&
                (req.body[key] !== null)) {
                req.body[key] = req.body[key]._id;
            }
        }

This depopulates fields, but only does so on the root fields, not subfields.

**Comment by Zertz** [comment]
If this is a nested Schema/ref, you should update it through it's own endpoint instead.

**Comment by ehmicky** [comment]
At the moment, you can actually update nested refs, providing they are at the root of the ref.
Updating a ref through its own endpoint requires an extra HTTP call, which I think is less efficient or simple.

**Comment by Zertz** [comment]
I wasn't even aware this was possible and, while it certainly is convenient, it's not a feature I agree with. It's also only more efficient if only the nested document has been updated, otherwise you're actually sending more data.

**However, if it's to be provided then, yes, it should recursively look for `_id` keys.**

**Comment by Zertz** [comment]
This needs a test to confirm, but ti should work in 2.x

**Comment by Zertz** [comment]
This was resolved in 2.3.0
