### ISSUE TITLE
Strings starting with logical operators in the database

### ISSUE THREAD

**Issue by pedrofurla** [florianholzapfel/express-restify-mongoose#111]
I am querying a field that contains strings like `"<something..."` and the query issued againts mongo ends up being replaced with something like `{ "$lt": "something"}`, my problem is that the actual data starts with `<`. How hard is it to have a flag that disables this replacement? Is there any other work around these?

**Comment by florianholzapfel** [comment]
this is currently not possible. i will add this in a future release.

then it should be possible do something like ```/api/v1/model?field==value``` which in your case could be ```/api/v1/model?field==<something...``` and should lead to ```{ "$eq": "<something..." }```
