### ISSUE TITLE
onError: Bad Request & ValidationError

### ISSUE THREAD

**Issue by leandono** [florianholzapfel/express-restify-mongoose#118]
Hi!
I'm trying to create a custom error handler for the validation errors of Mongoose. My code is something like this:

```js
onError: function(err, req, res, next){

	if(err.name === 'ValidationError'){

		res.status(err.status).json({
			status: 'fail',
			message: err.message
		});

	} else {

		res.status(err.status).json({
			status: 'error',
			message: err.message
		});

	}

}
```

The problem that I have is that always I get first a `Bad Request` error, and then, a `ValidationError` not allowing me to show the correct response in the last case. Is this behavior correct (two successive errors, first the  `Bad Request` and later the `ValidationError`)?

Cheers

PS: The problem happens in the two versions of the module.

**Comment by florianholzapfel** [comment]
Using version 1.0, I cannot reproduce this issue. I was using the [examples/invoicing.js](https://github.com/florianholzapfel/express-restify-mongoose/blob/master/examples/invoicing.js) sample.

After executing the following request

```
POST http://localhost:3000/api/v1/customers

{
    "name": null,
    "comment": "comment"
}
```

I get the following results.

Without your ```onError``` function:
```json
{
  "message": "Customer validation failed",
  "name": "ValidationError",
  "errors": {
    "name": {
      "properties": {
        "type": "required",
        "message": "Path `{PATH}` is required.",
        "path": "name",
        "value": null
      },
      "message": "Path `name` is required.",
      "name": "ValidatorError",
      "kind": "required",
      "path": "name",
      "value": null
    }
  },
  "status": 400
}
```

Using your ```onError``` function, I get the following output:
```json
{
  "status": "fail",
  "message": "Customer validation failed"
}
```

Do you have a working example for me to try?

**Comment by Zertz** [comment]
Are you using async mongoose hooks?

**Comment by leandono** [comment]
Finally I solve the problem, I was sending the parameters of the POST request as form-data and no as `application/json`, so for that the `Bad Request` before the `ValidationError`

Thank you guys!

**Comment by Zertz** [comment]
@florianholzapfel Clearly an edge case, but sending a response twice should never happen. Worth looking into?

**Comment by florianholzapfel** [comment]
I have tried to reproduce this: There is only one response sent.

**Comment by leandono** [comment]
To reproduce this:

#### invoicing.js
```js
var http = require('http');
var express = require('express');
var bodyParser = require('body-parser'),
	methodOverride = require('method-override');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var restify = require('..');

mongoose.connect('mongodb://localhost/database');

var Customer = new Schema({
	name: { type: String, required: true },
	comment: { type: String }
});
var CustomerModel = mongoose.model('Customer', Customer);

var Invoice = new Schema({
    customer: { type: Schema.Types.ObjectId, ref: 'Customer' },
	amount: { type: Number, required: true }
});
var InvoiceModel = mongoose.model('Invoice', Invoice);

var app = express();
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
app.use(methodOverride('X-HTTP-Method-Override'));
restify.serve(app, CustomerModel, {
	onError: function(err, req, res, next){

		console.error(err);

		next();

	}
});
restify.serve(app, InvoiceModel);

http.createServer(app).listen(3000, function () {
	console.log('Express server listening on port 3000');
});
```

#### CURL
```bash
curl -X POST -H "Cache-Control: no-cache" -H "Content-Type: multipart/form-data" -F "name=" http://localhost:3000/api/v1/customers
```

#### Response
```bash
$ node invoicing.js
Express server listening on port 3000
{ [Error: Bad Request] status: 400 }
{ [ValidationError: Customer validation failed]
  message: 'Customer validation failed',
  name: 'ValidationError',
  errors:
   { name:
      { [ValidatorError: Path `name` is required.]
        properties: [Object],
        message: 'Path `name` is required.',
        name: 'ValidatorError',
        kind: 'required',
        path: 'name',
        value: undefined } },
  status: 400 }
```

Cheers

**Comment by Zertz** [comment]
Okay, so what's happening is that the `ensureContentType` middleware properly finds out the request isn't `application/json` and calls `onError`. However, the problem here is that by calling `next()` in `onError`, the request continues as if the `write_middleware` had passed.

```
write_middleware > onError > next > createObject > onError
```

https://github.com/florianholzapfel/express-restify-mongoose/blob/master/lib/express-restify-mongoose.js#L358

**Comment by aderhm** [comment]
> Finally I solve the problem, I was sending the parameters of the POST request as form-data and no as `application/json`, so for that the `Bad Request` before the `ValidationError`
> 
> Thank you guys!

Hi.. Could you offer more explanation; what did you do to fix that err, I got the same one and I am a beginner so can not understand what's wrong!!

Thank You!!!

**Comment by Zertz** [comment]
The exact implementation will vary a bit depending on the library you're using to make http requests but the idea is to set the correct content type:

```
{
  headers: {
    "Content-Type": "application/json
  }
}
```
