### ISSUE TITLE
How to find by object id in query? 

### ISSUE THREAD

**Issue by xream** [florianholzapfel/express-restify-mongoose#120]
In mongoose , it should be
```
var ObjectId = require('mongoose').Types.ObjectId; 
var query = { campaign_id: new ObjectId(campaign._id) };
```

**Comment by florianholzapfel** [comment]
You can do this by using the following HTTP GET: ```/api/v1/models?campaign_id=campaign._id```. Just replace ```models``` with the name of the model that you have used and ```campaign._id``` with the string value of ```campaign._id```. E.g.: ```/api/v1/models?campaign_id=52172b19df5bab8816000001```

**Comment by xream** [comment]
@florianholzapfel Thank you! In fact, I want to do this: `/api/v1/logs?query={"meta._id":"=ObjectId(555651f78243f140b8143dd6)"}`.

**Comment by florianholzapfel** [comment]
This is possible by using ```/api/v1/logs?query={"campaign_id":"555651f78243f140b8143dd6"}```. I am not sure if it will work, if you are querying for an id stored in a subdocument.
