### ISSUE TITLE
community channels?

### ISSUE THREAD

**Issue by mgenev** [florianholzapfel/express-restify-mongoose#121]
hi,
I think i've found the perfect module to use for what I want to do:

1) express. check
2) mongoose. check
3) automatic rest crud generation. check

I would very much like to get involved, is there a channel where contributors hang out?

**Comment by Zertz** [comment]
Here?

Contributions are welcome, @florianholzapfel keeps an eye on PR's so if there's something you'd like to add or fix, feel free.
