### ISSUE TITLE
Add descriptions to cryptic errors

### ISSUE THREAD

**Issue by Zertz** [florianholzapfel/express-restify-mongoose#123]
I remember this has been brought up before, but I just stumbled upon such an issue and it is rather annoying to have to go look at the source to find the problem.

For example: https://github.com/florianholzapfel/express-restify-mongoose/blob/master/lib/express-restify-mongoose.js#L361

If an invalid or no `Content-Type` is present, all that is returned is `400 - Bad Request`, which is hardly helpful. I suggest adding a `description` field and perhaps spliting *missing* (`!ct`) and *invalid* (`-1 === ct.indexOf('application/json')`)

```
err.description = 'missing_content_type';
err.description = 'invalid_content_type';
```

This is mostly a reminder, I'll submit a PR later this week.

Is anyone aware of other similar cases?

**Comment by florianholzapfel** [comment]
After having a look on this, I think there are four cases like this:

 - https://github.com/florianholzapfel/express-restify-mongoose/blob/master/lib/express-restify-mongoose.js#L141
 - https://github.com/florianholzapfel/express-restify-mongoose/blob/master/lib/express-restify-mongoose.js#L361
 - https://github.com/florianholzapfel/express-restify-mongoose/blob/master/lib/express-restify-mongoose.js#L399
 - https://github.com/florianholzapfel/express-restify-mongoose/blob/master/lib/express-restify-mongoose.js#L451

All other errors are "404 Not found".

Also splitting both cases would lead to better error messages.

Thank you for your effort!

**Comment by Zertz** [comment]
I created a PR #124

Not exactly sure what the description should be for L141.

**Comment by florianholzapfel** [comment]
i have updated the code according to your suggestion and also added the missing error description
