### ISSUE TITLE
Allow space in private and protected attributes

### ISSUE THREAD

**Issue by ErikEvenson** [florianholzapfel/express-restify-mongoose#126]
Currently, if you put spaces in the string of fields, the fields are still passed through.

This will allow all fields through:

```
protected: '_id, __v, created, email, name, password, provider, salt',
```

This will not:
```
protected: '_id,__v,created,email,name,password,provider,salt',
```

**Comment by Zertz** [comment]
Yes, because it's a comma-separated list.

Since this really is a readability issue, I feel the better solution here is instead to pass an array of fields rather than tacking on whitespace removal. See PR #127

**Comment by ErikEvenson** [comment]
Fair enough -- I would prefer the array as well.  Thanks for the great tool!
