### ISSUE TITLE
POSTed fields in protected list are stripped

### ISSUE THREAD

**Issue by ErikEvenson** [florianholzapfel/express-restify-mongoose#130]
If I POST to an endpoint a body that has, say, a `password` field included, the `password` field is not saved to the model when the `password` field is included in the protected list.  That is, the field is stripped from the request prior to the database save.

Given the documentation:

`protected - String of comma separated field names which are not to be returned by queries that have public access.`

I would have expected the field to be saved but not returned in the body of the POST response.

Is the current state the intended behavior?

Cheers!

**Comment by Zertz** [comment]
> Is the current state the intended behavior?

Yes, however the documentation is confusing indeed and that option's documentation needs to be reviewed anyway since it also supports being given an array now.

Here's how I generally handle authentication and protected fields:

```javascript
restify.serve(router, AwesomeModel, {
    prereq: function(req) {
      if (!req.isAuthenticated()) {
        return false;
      }

      if (req.method.toLowerCase() === 'post') {
        req.body.user = req.user._id.toHexString();
      }

      return true;
    },
    access: function(req) {
      if (req.isAuthenticated() && req.method.toLowerCase() === 'post') {
        return 'protected';
      } else {
        return 'public';
      }
    },
    private: 'topSecret',
    protected: 'semiSecret',
    contextFilter: function(model, req, cb) {
      var query = {};
      
      if (req.method.toLowerCase() === 'put') {
        query.user = req.user._id;
      }
      
      cb(model.find(query));
    }
});
```

**Comment by TitForTat** [comment]
Hey @Zertz this is VERY helpfull. 

Thanks a bunch

**Comment by TitForTat** [comment]
In that example code, a logged user can't edit some one else's AwesomeModels, but they can still delete them, right? Sounds like a security issue.

**Comment by florianholzapfel** [comment]
this should not be possible because also DELETE requests are filtered through ```contextFiler```.

**Comment by Zertz** [comment]
@TitForTat That is correct, I unintentionally left it out because I always have this in front of my API :

    router.delete('/*', function (req, res, next) {
      res.sendStatus(403)
    })
