### ISSUE TITLE
Support for mongo text search

### ISSUE THREAD

**Issue by DavidBLynch** [florianholzapfel/express-restify-mongoose#131]
I've defined a full text index on a collection, and want to perform a [full text query](http://docs.mongodb.org/manual/reference/operator/query/text/) via REST using this library.  There is no documentation so I'm not sure if this is possible?

**Comment by Zertz** [comment]
I'm pretty sure it works, you just have to make the query URL safe.

```javascript
query: encodeURIComponent(JSON.stringify({
  $text: {
    $search: 'for stuff'
  }
})
```

**Comment by DavidBLynch** [comment]
That was what I was missing.  encodeURIComponent & JSON.stringify.  Works fine with this.  Suggest adding an explicit sample to the README.

**Comment by Zertz** [comment]
It's slightly buried, but it's there
