### ISSUE TITLE
fields not defined in the schema can never save to db?

### ISSUE THREAD

**Issue by chhaj5236** [florianholzapfel/express-restify-mongoose#132]
I was trying to update some fields but failed (nothing changed), and those fields were not defined in the schema. I found that _doc[key] = req.body[key]_ was used (file: express-restify-mongoose.js, line: 532) when options.findOneAndUpdate was set to false.

According to mongoose's docs: http://mongoosejs.com/docs/guide.html#strict
> Any key/val set on the instance that does not exist in your schema is always ignored, regardless of schema option.

If I understand it right: no matter how we set options.findOneAndUpdate(true or false), we can never save those fields not defined in the schema into db? Should we use _doc.set(key, req.body[key])_ instead? (I made this modification in my computer, and it worked. But I am not sure if I miss anything important.)

**Comment by florianholzapfel** [comment]
As you can control the ```strict``` behaviour when defining your models, I think this is the best place to do.

**Comment by chhaj5236** [comment]
Thank you for your reply. But I'm still a little confused, hope you can help me~.  I did set **strict** to **false** in my code. So I looked for mongoose's docs for help as the link I posted above. It says **regardless of schema option, key/value set on the instance is always ignored**. I also tried to debug and found out that no matter what the value of **strict** is, _doc[key]=req.body[key]_ would not modify doc._doc as expected when key was not defined in the schema.

**Comment by Zertz** [comment]
This is because mongoose isn't aware of the key if it's not in the schema. I'm guessing `doc.set(key, value)` uses `markModified(key)` internally.

Did you try running the tests with `doc.set(key, value)` ?

**Comment by chhaj5236** [comment]
Yes, @Zertz . I changed doc[key]=value to doc.set(key, value) in express-restify-mongoose.js. It worked.

**Comment by trsouz** [comment]
It happened to me too. And @chhaj5236 solution worked for me too!

**Comment by Zertz** [comment]
I don't like this because it allows the client to write arbitrary data into the database, which, needless to say, is unsafe.

**Comment by chhaj5236** [comment]
@trsouz I'm so glad it helps. @Zertz If we don't want the client to write arbitrarily, we can just set **strict** option to **true**, then doc.set(key, value) will not save the change into db.

**Comment by Zertz** [comment]
@chhaj5236 You are right. Feel free to create a PR!
