### ISSUE TITLE
Express Compression Issue

### ISSUE THREAD

**Issue by alefort** [florianholzapfel/express-restify-mongoose#133]
I added compression module to my express app as you have in the documentation. I added the compression module first, before the router, and now I get no response from my server. The requests just seem to sit, and sit and sit.

I'm assuming I'm doing something wrong, does anyone have an example of how to add gzip compression to the results from the express app that uses express-restify-mongoose ?

Cheers

**Comment by Zertz** [comment]
There is nothing special about this module and compression.

```javascript
var compression = require('compression')
var express = require('express')
 
var app = express()
app.use(compression())
 
// Routers
```

**Comment by alefort** [comment]
Pier-Luc, 

That's what I thought, and that's what I'm doing. But any restful GET call I make to an API served up by express-restify-mongoose just hangs if I add compression. If you are willing, can you review the following js file and see what might be wrong:

https://github.com/alefort/getcrafty/blob/master/api/api.js

^ I that version, compress isn't added to the app, I commented it out.

**Comment by florianholzapfel** [comment]
it should be ```app.use(compress());```` instead of ```app.use(compress);``` in https://github.com/alefort/getcrafty/blob/master/api/api.js#L19
