### ISSUE TITLE
Code formatting, switch to standard?

### ISSUE THREAD

**Issue by Zertz** [florianholzapfel/express-restify-mongoose#135]
[standard](https://github.com/feross/standard) has been gaining some steam lately and, IMHO, with good reason. It uses `es-lint` under the hood and supplies a set of rules. The obvious benefit is making code easier to read especially the parts with deep nesting.

```javascript
"devDependencies": {
  "standard": "^4.0.0"
},
"scripts": {
  "pretest": "standard"
}
```

**Comment by florianholzapfel** [comment]
@Zertz I think that is a good idea that will keep the code readable. I have started to edit the code to conform to standard's requirements. The code is present in the branch [dev-standard](/florianholzapfel/express-restify-mongoose/tree/dev-standard).

Currently there are two test failing. I will try to fix them as soon as possible.

**Comment by Zertz** [comment]
@florianholzapfel You're making your life harder than it has to be :)

You can simply run [standard --format](https://github.com/feross/standard#is-there-an-automatic-formatter)

**Comment by florianholzapfel** [comment]
that's what i did. but it did not automatically change everything about which it complains in the pre-test script.

**Comment by Zertz** [comment]
Oooh, sorry! It's definitely annoying in the beginning, but once you get the hang of it (and fight the semicolon urge) it really makes code prettier.

**Comment by florianholzapfel** [comment]
No need to say sorry. That is definitively improving the code.

**Comment by Zertz** [comment]
As a side note, I'll try to find some time within the next week to get test coverage back up.

**Comment by Zertz** [comment]
@florianholzapfel Do you need some help wrapping this up?

**Comment by florianholzapfel** [comment]
@Zertz thanks, but i just managed to find the cause of the failing test.
