### ISSUE TITLE
RESTify models with parent parameter

### ISSUE THREAD

**Issue by Evanion** [florianholzapfel/express-restify-mongoose#136]
Hello
Is it possible to RESTify models with a parent parameter?

example

````
https://api.example.com/:organization/users
https://api.example.com/:organization/invoices
https://api.example.com/:organization/issues
````

It feels like a more logical structure than:

````
https://api.example.com/users/:organization
https://api.example.com/invoices/:organization
https://api.example.com/issues/:organization
````

**Comment by florianholzapfel** [comment]
hi,
this is unfortunately not possible at the moment. i will leave that ticket open, because it could be nice to have this possibility in the future.

**Comment by Evanion** [comment]
Looking forward to it :+1:

**Comment by Zertz** [comment]
IMHO a REST interface should only have a single level and accept query parameters. The current `https://api.example.com/users/query={organization:id}` is simple, easy to read and makes sense.

What happens to the `https://api.example.com/:organization/users` endpoint when an organization happens to have a unique slug `users` ?
