### ISSUE TITLE
How to do a field validation when a create a new object?

### ISSUE THREAD

**Issue by jinwyp** [florianholzapfel/express-restify-mongoose#138]
For example , I want create a new new with username and mobile and password

How would I do the field validation , checking username and mobile not exist then POST request saved?

I check the document about prereq and access method, but I don't know how to use it, because checking username and mobile not exist  is a async process, I need wait the checking process before create a new user.

**Comment by Zertz** [comment]
There are examples in the wiki:

**prereq**: https://github.com/florianholzapfel/express-restify-mongoose/wiki/Options#prereq
**access**: https://github.com/florianholzapfel/express-restify-mongoose/wiki/Options#access

**Comment by jinwyp** [comment]
prereq and access can't do some async validation , I have use middleware to finish this .
