### ISSUE TITLE
Update gh-pages

### ISSUE THREAD

**Issue by Zertz** [florianholzapfel/express-restify-mongoose#139]
The [gh-pages](http://florianholzapfel.github.io/express-restify-mongoose/) docs are severely outdated and desperately need updating. The docs are currently incomplete and scattered (readme, wiki (*I'm guilty of this one*) and pages) which I think is a barrier to adoption.

Readme should only contain a "quick start", [this template](https://gist.github.com/zenorocha/4526327) being a pretty decent example. gh-pages should contain the complete API reference, code samples and so on. Wiki should be killed.

@florianholzapfel I'm willing to spend some time getting them up to date and centralized. Either through PR's or push access to that branch, whichever you prefer.

**Comment by florianholzapfel** [comment]
I am currently on vacation and having limited access. I will give you push access once I return.

**Comment by Zertz** [comment]
Enjoy your vacation !

**Comment by florianholzapfel** [comment]
thank you!

**Comment by Zertz** [comment]
It's still very much a work in progress, but I've made some commits in gh-pages-dev.

Loosely based on Bootstrap's documentation. It's just static HTML for now, so you don't need any special tooling if you want to have a look.

**Comment by Zertz** [comment]
@florianholzapfel I pushed changes to gh-pages. New layout, more examples. There is still plenty of room for improvement, but it's a step forward :)

**Comment by florianholzapfel** [comment]
it looks awesome. thank you very much for your efforts!
