### ISSUE TITLE
Return 'count' with query results

### ISSUE THREAD

**Issue by matthew-b-payne** [florianholzapfel/express-restify-mongoose#141]
For client api class that page results, it is much more convenient to make a single call and get results + count rather that manage two separate calls for results and count. I believe this lib should have this feature of at least the option to return query/search results in this manner.

Several other rest libs (yarm for example return results like this).  I believe another returns count via a response header.  

The simple mongoose paginate does this as well.  
https://github.com/edwardhotchkiss/mongoose-paginate/blob/master/lib/mongoose-paginate.js

  async.parallel({
    results: function(callback) {
      query.exec(callback);
    },
    count: function(callback) {
      model.count(q, function(err, count) {
        callback(err, count);
      });
    }
  }

Notice anyc calls being made to return an object containing results and count.

**Comment by Zertz** [comment]
Is there any reason not to simply read the length property on the client?

**Comment by matthew-b-payne** [comment]
If the client is paging page 1 with 161 results (17 pages) with a pageSize
of 10.  Length is only going to be 10, not 161.
e.g. not the total count from the query.


On Mon, Aug 17, 2015 at 4:21 PM, Pier-Luc Gendreau <notifications@github.com

**Comment by Zertz** [comment]
Yes, I realized that after I hit "Comment" ;)

**Comment by ravishivt** [comment]
+1, this would be very useful.  I took a stab at using outputFn but realized it was futile since the results are already filtered at that point.

```javascript
  outputFn: function(req, res, restifyRes) {
    if (restifyRes.result instanceof Array) {
      return res.send({
        _count: restifyRes.result.length,
        _items: restifyRes.result
      });
    }
    return res.send(restifyRes.result);
  },
```

I don't see a workaround since none of the options have access to the filtered model.

**Comment by Zertz** [comment]
You could implement a count query in `contextFilter`

**Comment by ravishivt** [comment]
@Zertz definitely not easy since the contextFilter doesn't have the filtered options provided in the requesting URL.  For example, the query: /api/v1/user-roles/?skip=1&limit=25&type=auto.   The "type=auto" would not be filtered in the contextFilter model so the calculated count would be much higher than the filtered count.

BTW, here's how I'm handling the issue in Angular with ui-grid's external pagination option.  I just use $q.all() to wait for both the paginated list query AND the /count query to return.

```javascript
var apiUrlCount = '/api/v1/user-roles/count/';
var apiUrl = '/api/v1/user-roles/?skip={0}&limit={1}'.format(
  (paginationOptions.pageNumber - 1) * paginationOptions.pageSize,
  paginationOptions.pageSize
);
$q.all([
  $http.get(apiUrlCount),
  $http.get(apiUrl)
]).then(function(data) {
  $scope.gridOptions.totalItems = data[0].data.count;
  $scope.gridOptions.data = data[1].data;
});
```

**Comment by Zertz** [comment]
I'm working on docs at the moment, but the internal implementation would be rather straightforward. The anonymous function at [line 622](https://github.com/florianholzapfel/express-restify-mongoose/blob/master/lib/express-restify-mongoose.js#L622) could be refactored into a named function and re-used somewhere around [line 592](https://github.com/florianholzapfel/express-restify-mongoose/blob/master/lib/express-restify-mongoose.js#L622)

**Comment by Zertz** [comment]
@ravishivt @matthew-b-payne See PR #218

Should land in the next few days...

**Comment by ravishivt** [comment]
I'm using this.  Works great, thanks!
