### ISSUE TITLE
Exclude option that excludes fields from all API queries

### ISSUE THREAD

**Issue by ravishivt** [florianholzapfel/express-restify-mongoose#143]
Where would I put a lists of fields to completely exclude from all requests?  Currently, the private, protected, and public provide three layers.  I have "private" fields mapped to only admin user access, protected mapped to only authenticated users, and public available to non authenticated users.  This doesn't leave me an option for a complete exclusion level.  I'm guessing I should alter the logic so the "private" request is never available making those fields actually be excluded.  However, I saw remnants in the code comments about a real "exclude" option.  Has that been abandoned?

**Comment by ravishivt** [comment]
The contextFilter is probably the best option here.  Closing this issue.

**Comment by arathael** [comment]
I currently have implemented this same behavior in my app for hiding passwords via the `ouputFn` method. I basically strip properties from objects (including populated ones). I'm curious about how you use it on your `contextFilter`, is it by selecting `-protectedField`? What about nested refs?

**Comment by Zertz** [comment]
@arathael You can do this within `contextFilter`:

```javascript
cb(model.find(query, {
  firstname: 1,
  lastname: 1
}).populate({
  path: 'team',
  select: '_id name'
}))
```

**Comment by arathael** [comment]
But that way I break the population and fields queried, right? It doesn't matter if I do
```http
GET /Orders?populate=user&select=user.picture
```
Because when `contextFilter` runs it will override my query.

**Comment by Zertz** [comment]
Yes, the query in `contextFilter` will override the client request. If I recall correctly, this behavior comes from mongoose.

**Comment by arathael** [comment]
Yeah, well that is not the behavior I'm looking to implement. I would like my app to hide all the `passwordHash` properties in any client object, even when queried. But still have the flexibility of making my own client-side queries.

**Comment by Zertz** [comment]
In that case, yes, `outputFn` is your best bet at the moment
