### ISSUE TITLE
Support for Query.read('ReadPreference.x')

### ISSUE THREAD

**Issue by Zertz** [florianholzapfel/express-restify-mongoose#147]
When reading from a replica set, there is currently no easy way to read from anything but the primary. The application should trigger some sort of maintenance mode to disable writes, but it would be useful if the library exposed [`.read()`](http://mongoosejs.com/docs/api.html#query_Query-read) to prevent downtime until a secondary is promoted.

I'm thinking something like this:

```javascript
restify.defaults({
  readPreference: 'primary'
})
```

**Comment by Zertz** [comment]
Actually, there is an easy way to set read preference on a replica set.

```javascript
var connection = mongoose.createConnection('mongodb://replicaset_uri', {
  replSet: {
    readPreference: 'ReadPreference.PRIMARY_PREFERRED'
  }
})
```

**Comment by mattcasey** [comment]
Hi, I need this to be per request, or at least per collection. We're using this lib to serve our primary internal api but our analytics builders need to query secondary or they slow everyone else down. 

Can maintainers suggest a better fix? We will probably add support ourselves, ideally in a way that can be merged back to the primary code.
