### ISSUE TITLE
Provide the current model object to prereq if findOneAndUpdate is set to false

### ISSUE THREAD

**Issue by ravishivt** [florianholzapfel/express-restify-mongoose#148]
After working with other API libraries and after going through the "write your own API with mongoose" tutorials, the common workflow is to have the original DB object in the API methods.  This is done in express using the .param() function in the route defintions.  Having the original object is useful when you want to compare it with the original object.

For example, let's say you have a User collection with an array of referenced UserRole objects.  Some of the user roles should be system defined, aka read-only, where the API should not be allowed to remove or add on a particular user.  Other roles should be allowed to remove/add.  If we had the original DB object, we could iterate through the original User object's roles, find which system-defined roles the user already has, and make sure those exact system-defined roles and only those system-defined roles are in the req.body.

I understand that findOneAndUpdate default's to true to reduce the number of DB calls but if it's set to false, we are already doing two calls.  Why not do that first call earlier and pass it to the prereq function?

If there is a better way to accomplish the example provided, please let me know.  I know the mongoose validation function could possibly work but there are use cases where you only want to enforce the logic in the API and not the model level.  Such as allowing other backend calls to add the system-defined roles but not through the API.

**Comment by ravishivt** [comment]
To workaround this, I was able to use middleware as described in https://github.com/florianholzapfel/express-restify-mongoose/issues/60 to fetch the model and attach it to req object for future reference in the API methods.  It would still be nice to automatically pass the object to prereq since with findOneAndUpdate: false, there are three DB calls.  One to fetch the obj in the middleware, and the other two to find the object and update it.

Another question, why don't all of the API methods (prereq, access) support asynchronous logic?

**Comment by Zertz** [comment]
@ravishivt prereq and access both support async, here's the [updated documentation](http://florianholzapfel.github.io/express-restify-mongoose/)

If I understand correctly, I think you're looking for a way to define `private` and/or `protected` on a request basis rather than globally on the endpoint. Is that correct?

**Comment by ravishivt** [comment]
@Zertz I like the new documentation!  Nice work.

Having a way to conditionally make fields private and protected based on the request would be nice.  But some use cases require a more granular approach.  Such as in a many-to-many relationship where you want to allow the API to edit some of the references but not others.  For example, a User has many UserRoles but some UserRoles are added by the authentication system and others are addable through the API.  The API should not be allowed to remove or add system defined roles but should be able to add/remove API accessible ones.  The only way to do this would be look at the object in the request and compare it to the targeted object it is trying to update to ensure the request isn't modifying the system defined roles.  So my feature request here is to retrieve the targeted object on GET, PUT, and DELETE requests and make it available to all methods such as prereq and access.

**Comment by Zertz** [comment]
Thanks!

`prereq` and `access` are too early in the flow to supply the object. For GET, you can hook onto `outputFn`. For PUT and DELETE it sounds like you'd need a hook [here](https://github.com/florianholzapfel/express-restify-mongoose/blob/master/lib/express-restify-mongoose.js#L533) and [here](https://github.com/florianholzapfel/express-restify-mongoose/blob/master/lib/express-restify-mongoose.js#L754).

I'm currently working on getting a huge release out, but this is within the realm of possibility.

**Comment by ravishivt** [comment]
Thanks for the suggestions.  I ended up solving this using my own custom middleware that fetches the object and makes it available in the req object.  Looking forward to the new release!

```javascript
function cleanReqBody(req, res, next) {
    if (req.method === 'PUT') {
        // Do not allow the API to add/remove references to "auto" type user roles.
        var originalAutoRoles = R.filter(R.whereEq({type: 'auto'}), req.locals.user.roles);
        var reqStrippedAutoRoles = R.filter(R.whereEq({type: 'manual'}), req.body.roles);
        req.body.roles = R.concat(reqStrippedAutoRoles, originalAutoRoles);
    }
    next();
}

// On ID targeted routes, retrieve the targeted object using the ID in the URL.
app.use(
	'/api/v1/users/.+',
	function(req, res, next) {
		if (req.method === 'GET' || req.method === 'PUT' || req.method === 'DELETE') {
			User.load(req.body.id, function (err, user) {
				if (err) {
					return next(err);
				}
				if (!user) {
					return next(new Error('not found'));
				}
				req.locals = req.locals || {};
				req.locals.user = user;
				next();
			});
		}
		else {
			next();
		}
	},
	cleanReqBody
);
app.use(router);
```

**Comment by Zertz** [comment]
@ravishivt I *really* like your suggestion! Ideally, I'd want `preUpdate` and `preDelete` to have access to the document rather than adding yet another hook. Would that work for you? If so, we just need to figure out a clean way to do that, given that `contextFilter` still needs to run before the find query.

So when `findOneAnd*` options are disabled, these methods needs to skip the pre middleware, jump to the find query, run the pre hooks and access and then go back to the actual update/remove.

**Comment by Zertz** [comment]
@ravishivt Take a look at #177 when you have a minute, let us know if that works for you

**Comment by ravishivt** [comment]
Sorry for the delay @Zertz.  I've tested this and it works great.  Really useful feature.  My only wish is that it would be called earlier in the chain so preMiddleware also had access to the document.

**Comment by Zertz** [comment]
@ravishivt that is by design actually, there is nothing that fundamentally prevents what you're suggesting, but I wanted to keep the first hook very early in the request.
