### ISSUE TITLE
PUT Returning 404

### ISSUE THREAD

**Issue by kauegimenes** [florianholzapfel/express-restify-mongoose#149]
Hello, for some reason i can`t make PUT requests they aways get the response code 404 after a OPTIONS 204 request. 

````
OPTIONS /api/v1/Users 204 1.738 ms - -
PUT /api/v1/Users 404 381.181 ms - 14
````

The other HTTP methods work:
````
GET /api/v1/Users 200 9.749 ms - 59
````

 I am currently using https://github.com/expressjs/cors to handle CORs

**Comment by Zertz** [comment]
`PUT /api/v1/Users` isn't a valid endpoint as it's meant to update an existing resource.

You can `POST /api/v1/Users` and `PUT /api/v1/Users/some-id`

**Comment by Zertz** [comment]
@kauegimenes Did that work for you?

**Comment by kauegimenes** [comment]
@Zertz That make sense ;) but i still didn't had time to test it.

**Comment by Zertz** [comment]
@kauegimenes Alright!, I'll close this for now, feel free to re-open if you're still having issues.
