### ISSUE TITLE
Manually define _id

### ISSUE THREAD

**Issue by ivansabik** [florianholzapfel/express-restify-mongoose#150]
Hi great package, I'm starting to test it out but I have a question if it is possible to do this. Namely I need to manually assign the _id for all resources.
I tried with the example provided:

POST http://localhost:3000/api/v1/customers/154
With body:
```
{
     "name": "Johnny Soy"
}
```
I also tried POST http://localhost:3000/api/v1/customers/ with body:
```
{
    "_id": 154,
     "name": "Johnny Soy"
}
```
and:
```
{
    "id": 154,
    "name": "Johnny Soy"
}
```
But it seems that you can only POST the route ```/:id``` if you have previously created it (only update, no create). Is it possible to manually assign the mongo ID when creating resources??

**Comment by Zertz** [comment]
Did you define an `_id` field in your mongoose schema?

**Comment by ivansabik** [comment]
Not yet, I'm starting to work with Mongoose so I'll try to define that as ```_id: { type: Schema.Types.ObjectId}```

The POST request should be to /customers or /customers/154??

**Comment by Zertz** [comment]
Since you need custom id's, you should use `_id: { type: Number }` or `_id: { type: String }`.

POST `{ "_id": "123", "someProperty": "hello" }` to `/customers`

**Comment by ivansabik** [comment]
thankz zertz ill try out and post my findings

**Comment by ivansabik** [comment]
I wasn't able to manually assign the mongo ID however I didn't need to do so. At the end I used the idProperty option:

```javascript
var opts = { idProperty: 'customer_id' };
var router = express.Router();
restify.serve(router, CustomerModel, opts);
```
