### ISSUE TITLE
Please upgrade "mongoose": "^4.1.6" for node v4.0.0

### ISSUE THREAD

**Issue by lgaticaq** [florianholzapfel/express-restify-mongoose#151]

**Comment by Zertz** [comment]
`"mongoose": "^4.0.0"` matches `4.1.6`

From http://jubianchi.github.io/semver-check/
> ^4.0.0 is a range (caret) constraint. It means that it will match several versions.
> In fact, the current constraint will be satisfied by any version matching >=4.0.0 <5.0.0.

**Comment by florianholzapfel** [comment]
the released version (1.0.3) had a ```~4.0.0``` constraint that didn't match version ```4.1.6```. This was changed. I have pushed a new version to npm (1.0.4).
