### ISSUE TITLE
Specify outputFn for different endpoints

### ISSUE THREAD

**Issue by i4got10** [florianholzapfel/express-restify-mongoose#164]
Hi!
 
In parameters you can pass outputFn, but it applies to all possible endpoints in the application for the current model. 

For example, I would like to redefine the server response to the collection request(``GET http://localhost/api/v1/Customers``), adding some fields or wrapping them in object. 

Anyway can I achieve this?

**Comment by Zertz** [comment]
You can use conditions based on the request's method:


```javascript
if (req.method === 'GET') {
  ...
}

```

Does that help?

**Comment by i4got10** [comment]
Nope :( There are many possible GET request`s

```
GET http://localhost/api/v1/Customers/count
GET http://localhost/api/v1/Customers
GET http://localhost/api/v1/Customers/:id
GET http://localhost/api/v1/Customers/:id/shallow
```

Right now, I have something like below. Working good, but its totally hacked and used internal libs, which not exported.

```js
module.exports.getCategoriesWithProducts = function (req, res) {
    buildQuery({})(Category.find(), req._ermQueryOptions)
        .lean()
        .then(function (categories) {
            var ids = _.pluck(categories, '_id');

            return Product.find({company: req.query.company, category: {$in: ids}}).lean().then(function (products) {
                products.forEach(function (product) {
                    var category = _.find(categories, {_id: product.category});
                    category.product = product;
                });

                return categories;
            });
        })
        .then(function (categories) {
            return res.status(200).json(categories);
        })
        .catch(function (err) {
            return res.status(400).json({
                error: err.message
            });
        });
};
```

**Comment by Zertz** [comment]
Hmm, I can't think of a clean solution to that. Basically, you only want to run this on `/categories`?

What you could do is either add `products: [{ type: ObjectID, ref: 'Product' }]` in the category schema or make two separate calls to the API.

As a side note, I see from `_ermQueryOptions` that you must on the `refactor-anon-functions` branch? I can tell you this particular part of the code won't change, *for now*.

**Comment by i4got10** [comment]
> As a side note, I see from _ermQueryOptions that you must on the refactor-anon-functions branch?

Yep, I grabbed code from your branch.
  
> What you could do is either add products: [{ type: ObjectID, ref: 'Product' }] in the category schema or make two separate calls to the API.

No, I cant. Each product has linked to Category and Company, so there is no way to populate products via Category.

> Basically, you only want to run this on /categories?

Yes. I think you can expose some part of lib like ``buildQuery``, so everyone can easily write own custom controllers. Second solution is to provide some identity of which kind of query is running now in ``outputFn``

**Comment by florianholzapfel** [comment]
you could additionally evaluate the ```result``` parameter. If it is an array, it was a call to ```/categories```. this is of course more difficult, it is is an object or ```null```, but in your case it probably would do.

but i think that exposing ```buildQuery``` and providing some kind of identity to ```outputFn``` would both be useful for the users of this library.

**Comment by Zertz** [comment]
It's a bit dirty, but `outputFn` supplies the `req` object so you could use that to get `req.path`

**Comment by Zertz** [comment]
We can use `query.op` internally to get `find`, `findOne` or `count` and set it in `req.erm.op`.
