### ISSUE TITLE
Move mongoose to peerDependencies

### ISSUE THREAD

**Issue by i4got10** [florianholzapfel/express-restify-mongoose#165]
Hi!

Right now, my application uses ``"mongoose": "~4.1.7"``. But express-restify-mongoose has a mongoose as direct dependency ``"mongoose": "~4.0.0"``. In this situation, some of my mongo requests will be go pass one version of mongoose, and other REST part in another.

![2015-09-25_1345](https://cloud.githubusercontent.com/assets/1151154/10096531/c3ce2892-638b-11e5-9528-87a465dd8842.png)

It would be great to move mongoose to peerDependencies, so user application can decide which version of mongoose to choose.

    "peerDependencies": {
      "mongoose": "^4.0.0"
    }

**Comment by Zertz** [comment]
It should already be ^4.0.0, which version are you on? Also peer dependencies have been removed in npm 3

**Comment by i4got10** [comment]
peerDependencies will not be removed, its a correct way to require a dependency in libs

http://blog.npmjs.org/post/110924823920/npm-weekly-5
> We will also be changing the behavior of peerDependencies in npm@3. We won’t be automatically downloading the peer dependency anymore. Instead, we’ll warn you if the peer dependency isn’t already installed. This requires you to resolve peerDependency conflicts yourself, manually, but in the long run this should make it less likely that you’ll end up in a tricky spot with your packages’ dependencies.

**Comment by Zertz** [comment]
My bad, you are entirely correct! It would make sense to have it as a peer, feel free to submit a PR.

**Comment by i4got10** [comment]
thanks!
