### ISSUE TITLE
Undocumented feature: sorting by multiple attributes

### ISSUE THREAD

**Issue by charlieclark** [florianholzapfel/express-restify-mongoose#167]
in addition to sorting like this

`http://localhost/api/v1/Customers?sort=name`

the library also supports sorting by multiple attributes

` http://localhost/api/v1/Customers?sort={"foo":1, "bar":-1 }`

**Comment by Zertz** [comment]
Thanks a lot! I've merged your post in #166

There are actually quite a few things to document so we'll try to keep it centralized :)

**Comment by charlieclark** [comment]
Great! 
Awesome library btw :+1:
