### ISSUE TITLE
Somebody screwed up

### ISSUE THREAD

**Issue by arathael** [florianholzapfel/express-restify-mongoose#178]
Using `v2.2.0` my previous succeeding tests fail miserably. I'm currently tracking which one of you to blame. Undesired behavior detected includes querying two models in a same route. Ex:

Having `Model1` and `Model2`

```http
GET /Model1/:id
```
Should query mongoose Model1, which does (let's assume).

Now
```http
GET /Model2/:id
```
Queries both Model1 and Model2, resulting in a 404 because Model1 has no document with that id at all.

Previous versions of this library don't trigger that behavior (including v2.1.0).

I will spend my morning trying to debug your files. I will be on you. I will not rest. You will fix this.

**Comment by arathael** [comment]
using `v2.1.2` does not experience this issue, i'm still testing.

**Comment by Zertz** [comment]
First off, change your tone. **This is unacceptable.**

Secondly, provide a sample to reproduce this issue.

**Comment by arathael** [comment]
Its business cat tone, i thought you'd get it. Anyway, challenge accepted. I'll post your homework.

**Comment by arathael** [comment]
I'll close this as is being reviewed in #182 .

**Comment by Zertz** [comment]
@arathael fix is on npm as `2.3.0-rc.1`

**Comment by arathael** [comment]
Hey thanks for fixing it.

**Comment by Zertz** [comment]
Thank @dvlsg
