### ISSUE TITLE
Using customDefaults expands preUpdates across models when findOneAndUpdate is falsy

### ISSUE THREAD

**Issue by dvlsg** [florianholzapfel/express-restify-mongoose#182]
I believe using `.defaults()` without a pre-update defined results in pre-updates being attached for multiple unintended models. Here's a quick example to reproduce:

```js
var express = require('express')
var bodyParser = require('body-parser')
var methodOverride = require('method-override')
var mongoose = require('mongoose')
var restify = require('express-restify-mongoose')
var app = express()
var router = express.Router()

app.use(bodyParser.json())
app.use(methodOverride())

mongoose.connect('mongodb://localhost/database')

var model1 = mongoose.model('model1', new mongoose.Schema({ stuff1: { type: String } }));
var model2 = mongoose.model('model2', new mongoose.Schema({ stuff2: { type: String } }));

restify.defaults({ findOneAndUpdate: false }); // important
restify.serve(router, model1);
restify.serve(router, model2);

app.use(router)

app.listen(3000, function () {
  console.log('Express server listening on port 3000')
})

// an update for model2 will fire filterAndFindById first for model2, then model1
```

In order to prove that this is being done, I added some logs to filterAndFindById.js on the filteredContext.modelName, as well as logs to express-restify-mongoose.js just before `return uri_items` to show that `options.preUpdate` contained filterAndFindById twice for model2, and once for model1.

A potential fix is to surround `customDefaults` with `_.clone()` at [express-restify-mongoose.js](https://github.com/florianholzapfel/express-restify-mongoose/blob/master/lib/express-restify-mongoose.js#L9) -- this is functional for resolving the fix at least, and all tests continue to pass. There might be a better way of doing it, though.

Side note, I believe this is also happening for preDeletes.

**Comment by Zertz** [comment]
Thanks for the detailed report, I'll look into it

**Comment by Zertz** [comment]
@dvlsg I think removing these form defults should fix this issue:

```javascript
preMiddleware: [],
    preCreate: [],
    preRead: [],
    preUpdate: [],
    preDelete: [],
    private: [],
    protected: [],
    postCreate: [],
    postRead: [],
    postUpdate: [],
    postDelete: []
```

**Comment by dvlsg** [comment]
Yup, I will try to write one up at some point today, when I have time -- I'm actually running into a few issues with just removing the `pre` and `post` arrays from the `getDefaults()` method. How do you feel about the following pattern? It does add quite a few lines of code, since I have to run it for each pre and post. Could shuffle it off to a local helper function, since the code is really repetitive. 

```js
  // changes for preMiddleware
  // remove line preMiddleware: [] from getDefaults()

  ...

  if (options.preMiddleware === undefined) {
    options.preMiddleware = []
  }

  // could use an else if here, as well
  if (!_.isArray(options.preMiddleware)) {
    options.preMiddleware = [options.preMiddleware]
  }
```

**Comment by Zertz** [comment]
We actually both came up with the same solution, just [expressed differently](https://github.com/florianholzapfel/express-restify-mongoose/blob/tests-filter/lib/express-restify-mongoose.js#L68).

However, I'm thinking the best fix is probably not to `splice` and `push` on user-provided options.

Can you try removing:

```javascript
if (!options.findOneAndUpdate) {
  options.preUpdate.splice(0, 0, filterAndFindById)
}
```

...and replace [this line](https://github.com/florianholzapfel/express-restify-mongoose/blob/master/lib/express-restify-mongoose.js#L167) with:

```javascript
app.post(uri_item, prepareQuery, ensureContentType, options.preMiddleware, options.findOneAndUpdate ? []: filterAndFindById, options.preUpdate, ops.modifyObject, prepareOutput)
```

Does that fix the issue?

**Comment by dvlsg** [comment]
I agree about the user-provided options, and yes -- what you have in the `tests-filter` branch mixed with your suggestion above looks great!

Still want a PR? I think I would just be re-doing what you have already done in the other branch.

**Comment by Zertz** [comment]
I think the bug still exists in that branch?

**Comment by dvlsg** [comment]
Fair point -- I dropped a pull request (sans unit tests, still deciding where to put those) which is more-or-less a merger of what was in [tests-filter](https://github.com/florianholzapfel/express-restify-mongoose/tree/tests-filter) and what was discussed here.
