### ISSUE TITLE
How to query embedded document ?

### ISSUE THREAD

**Issue by jinwyp** [florianholzapfel/express-restify-mongoose#188]
I want to query "db.inventory.find( { 'producer.company': 'ABC123' } )"

I use the query  url "/inventory?query={"producer.company":"ABC123"}" , but it is not working, return empty result.

**Comment by Zertz** [comment]
I've added a test and it passes. What happens when you query for it directly with mongoose?

**Comment by jinwyp** [comment]
Sorry, Now it works on mongoose 4.2.3
Maybe I used the old version mongoose or express-restify-mongoose 1.3 cause this problem.

**Comment by Zertz** [comment]
No worries, versions prior to 2.x didn't handle nested fields in most cases
