### ISSUE TITLE
Read from secondary (either per collection or request)

### ISSUE THREAD

**Issue by mattcasey** [florianholzapfel/express-restify-mongoose#189]
Hi, I need the option to query slaves per request, or at least per collection, since many different apps use our internal api that's served by this library. Can maintainers suggest a fix? We can probably add support ourselves, ideally in a way that can be merged back to the primary code.

Alternatively, maybe we can add middleware that modifies the query before execution? Haven't looked at the latest version of this repo to see if that's possible...

**Comment by mattcasey** [comment]
related issue: https://github.com/florianholzapfel/express-restify-mongoose/issues/147 (the fix doesnt work because it means ALL queries will go to secondary)

**Comment by Zertz** [comment]
Giving access to the mongoose query object is definitely something that would offer a lot more flexibility.

The simple fix at the moment is to use `.read()` similarly to how we use `.lean()`, which to to always add it to the query chain and provide a default that can be overidden with an option.

**Comment by mattcasey** [comment]
Thanks! I updated it on our fork of this library (still running on 1.0.3), also submitted a PR for the newer version: https://github.com/florianholzapfel/express-restify-mongoose/pull/190

**Comment by Zertz** [comment]
Closed by #190
