### ISSUE TITLE
Readonly mode

### ISSUE THREAD

**Issue by asaf-romano** [florianholzapfel/express-restify-mongoose#193]
We've something like this in our code base:
```js
            preMiddleware(req, res, next)
            {
                if (req.method != "GET")
                {
                    throw new Error("The ... collection is readonly");
                }
....
            }
```

This seems like a common use case that could be expressed with a readOnly configuration option.

**Comment by Zertz** [comment]
I'd rather not because there is no generic response to a read-only endpoint. For example, I have collections that are read-only for everyone (403, Forbidden), some are for a set of users (401, Unauthorized) and you throw.

**Comment by gaarf** [comment]
I believe the proper response for such a `readOnly` endpoint would be 405, _Method Not Allowed_.

**Comment by Zertz** [comment]
You can use `preCreate`, `preUpdate` and `preDelete` to implement this and return the response you deem to be correct.
