### ISSUE TITLE
Why was "custom method chaining" support removed?

### ISSUE THREAD

**Issue by ravishivt** [florianholzapfel/express-restify-mongoose#194]
I was looking to add custom methods to an ERM API and the approach described in #129 looked nice and clean.  In the 2.0 changelog, it states ```changed serve to no longer returns an Express 4 router, now returns the resource's base path (ie.: /api/v1/Customer)```.  Just curious on why?  I couldn't find the checkin that corresponded to the change that might give an explanation.

**Comment by Zertz** [comment]
Sorry, this change is somewhere in the 2.0 PR. The reason being that it only worked with Express 4.

I'm certainly open to a better solution, perhaps to bring back chaining and leave Express 3 and restify with the uri.

What you can do at the moment is this:

```javascript
var uri = resity.serve(router, Model, {
  ...
})

router.get(uri + '/:id/custom', function (req, res, next) {
  ...
})
```

**Comment by ravishivt** [comment]
That works for me, thanks.

**Comment by Zertz** [comment]
@ravishivt Closing this for now, feel free to re-open if you think we should bring it back
