### ISSUE TITLE
[discussion] The restify PUT is actually a PATCH?

### ISSUE THREAD

**Issue by KATT** [florianholzapfel/express-restify-mongoose#196]
Correct me if I'm wrong, but when doing `PUT` you're supposed to supply the full new resource representation that's going to replace the old one? 

What restify actually is doing is applying the delta via a `$set` of the keys that you sent. This should be considered a PATCH.

**Comment by Zertz** [comment]
Yes, it's technically a PATCH.

**Comment by KATT** [comment]
Could we clone the functionality for `PUT` under `PATCH`? It would make me feel way more safe. :blush:

**Comment by KATT** [comment]
I could PR it.

**Comment by Zertz** [comment]
@florianholzapfel What do you think about this?

My only concern is having 3 methods that perform the same action, but that could be cleaned up later in a major.

**Comment by KATT** [comment]
In a proper major you should probably remove current `PUT` or make it behave like an actual `PUT`. The REST APIs I make usually just need a `PATCH`.

**Comment by Zertz** [comment]
Yes

**Comment by florianholzapfel** [comment]
I would make the current PUT a PATCH and probably introduce a correct PUT. As this is a breaking change it should be introduced in a major release.

**Comment by Zertz** [comment]
Also, should we leave the POST update?

**Comment by florianholzapfel** [comment]
In my opinion, we should remove it. What do you think?

**Comment by Zertz** [comment]
Since changing these will break *alt* users, I think introducing PATCH now and deprecating POST/PUT would be a good approach. Using POST to update resources is certainly non-standard so removing it makes sense and also eases maintenance. Changing the behavior of PUT is also technically correct, but it can have dangerous side effects on client apps using PUT at the moment. This needs to be clearly communicated in a prior release IMO.

@KATT Can you PR a PATCH method?

**Comment by KATT** [comment]
:point_up_2: :point_up_2: :point_up_2: :point_up_2:

**Comment by dschoeni** [comment]
Maybe support for "proper" patching resources using the [JSON-Patch standard (RFC 6902)](http://tools.ietf.org/html/rfc6902) would be a great thing. I solved it using this [jsonpatch-to-mongodb](https://github.com/mongodb-js/jsonpatch-to-mongodb) library and hooking into `preUpdate`.

Could be a flag though, as of course, as your requests also need to follow the standard than.

**Comment by Zertz** [comment]
@dschoeni Aside from RFC compliance, what would be the benefit compared to the current approach?

**Comment by KATT** [comment]
+1 

It's simply more powerful. You can mutate deep properties without sending the whole object, and you could add custom operations too I guess?

A bit more annoying for the clients too maybe. :)

**Comment by dschoeni** [comment]
@Zertz reason was that my application actually needs to update properties of objects that are contained within an array.

Small example: Suppose I'd like to add another alias to John:
```
{
   name: John
   aliases: [{name: 'Pete'}, {name: 'Paul'}]
}
```

There is no way to simply add an object to this array, as the following PATCH replaces the array.

```
PATCH
{
   aliases: [{name: 'Tom'}]
}

GET
{
   name: John
   aliases: [{name: 'Tom'}]
}
```

You could create seperate models/documents out of them, but I guess there are a bunch of cases where embedding the documents makes more sense. 

Same goes for deep properties when I remember it correctly.
