### ISSUE TITLE
"query" URL param on DELETE possible?

### ISSUE THREAD

**Issue by wesratcliff** [florianholzapfel/express-restify-mongoose#201]
Is it possible to supply query parameters to filter a DELETE query?

For instance: `{{apiUrl}}/api/v1/model?query={"field":"value"}`

Looking through the issue history of the deprecated option `strict`, it looks like delete queries accepted URL query parameters in the past, however `prepareQuery` is not included in the delete middleware chain for the current version.

Is there another, recommended, built-in way to accomplish multiple item deletes with a query-style filter applied?

Thank you!

**Comment by Zertz** [comment]
This is definitely an oversight, thanks for bringing it up!

If you want to give it a shot, it should be a pretty straightforward PR. `prepareQuery` should indeed be part of the middleware chain and some tests should be added as well.

**Comment by wesratcliff** [comment]
Happy to do that -- will submit a PR + tests.

**Comment by Zertz** [comment]
@wesratcliff Perfect!
