### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by robhicks** [florianholzapfel/express-restify-mongoose#204]
What approaches are being used to provide api security when using express-restify-mongoose?

Does express-restify-mongoose provide any security mechanisms to protect routes/verbs/schema actions/elements?

**Comment by Zertz** [comment]
We provide the hooks, but security is left up to the user.

Usually, `preMiddlware` is a good place for authentication and the `preCreate/Read/Update/Delete` for authorization.

**Comment by robhicks** [comment]
That helps a great deal. Thanks!

**Comment by Zertz** [comment]
Good to hear!

The docs are a little weak in that area, we could probably come up with more examples.
