### ISSUE TITLE
Running tests on multiple Express/Restify versions

### ISSUE THREAD

**Issue by Zertz** [florianholzapfel/express-restify-mongoose#207]
With Express 5 on the horizon and our restify dependency already a major behind, this is something that should be looked into.

Any idea how we could run the tests of multiple versions?

**Comment by florianholzapfel** [comment]
As far as I know, npm does not support to install multiple versions of the same dependency. But there is a work around: npm supports different versions of the same packages in different dependencies and npm does support github urls as dependencies.

We could create github hosted npm packages that just export the specific express versions. E.g.: https://github.com/florianholzapfel/npm-express-4

package.json:
```
devDependencies: {
  "express-4": "git@github.com:florianholzapfel/npm-express-4.git"
}
```

test.js:
```
var express4 = require('express-4');
```

This is just a thought. I don't have tested it and don't know if it will work.

What do you think?

**Comment by Zertz** [comment]
That's clever! Either that or bump our major to drop support for previous versions.

ie.:

```javascript
erm-2: restify 3 + express 4
erm-3: restify 4 + express 4
erm-4: restify 4 + express 5
```

I guess it depends on the breaking changes. Right now a few features are hard to implement because of having to support both restify and express, it really depends what kind of changes are introduced in their majors.

Definitely less maintenance work to only support the latest stable major though.
