### ISSUE TITLE
Populate and match

### ISSUE THREAD

**Issue by cortezcristian** [florianholzapfel/express-restify-mongoose#208]
Acording to Issue #78 this is already implemented
```
/api/v1/Customers?populate={"path":"invoice","match":{"code":"ABC"}}
```
Is this working?

## Test case

0. When I populate with just the `path`, it works:
```
/api/v1/pacientes?populate={"path":"doctor"}
```
1. But when I add the `match` parameter:
```
/api/v1/pacientes?populate={"path":"doctor","match":{"drname":"Mario"}}
```
*Actual result:* I get `"doctor":null`

*Expected result:* get the document populated

I tested with:
```
$ npm list | grep mongoose
├─┬ express-restify-mongoose@2.3.0
├─┬ mongoose@4.0.0
....
```

**Comment by Zertz** [comment]
Thanks for reporting this! I'll put some tests together to figure out what's going on here.

**Comment by peek4y** [comment]
Any updates on this bug?

**Comment by Zertz** [comment]
We'll be releasing 3.0 in the near future, I'll try my best to include a fix.

**Comment by Zertz** [comment]
@cortezcristian @peek4y

I just ran the following test case against 2.4.2 and it seems to work as expected.

```js
it('GET /Invoices?populate={path:"customer",match={name:"Bob"}} 200', function (done) {
  request.get({
    url: util.format('%s/api/v1/Invoices', testUrl),
    qs: {
      populate: JSON.stringify({
        path: 'customer',
        match: {
          name: 'Bob'
        }
      })
    },
    json: true
  }, function (err, res, body) {
    assert.ok(!err)
    assert.equal(res.statusCode, 200)
    assert.equal(body.length, 3)
    body.forEach(function (invoice) {
      assert.ok(!invoice.customer || invoice.customer.name === 'Bob')
    })
    done()
  })
})

// invoice.customer:
// { "name": "Bob" }
// null
// null
```

Can you open `node_modules/express-restify-mongoose/lib/buildQuery.js` and add `console.log(queryOptions.populate)` below [line 27](https://github.com/florianholzapfel/express-restify-mongoose/blob/master/lib/buildQuery.js#L27) and post the output here?

**Comment by cortezcristian** [comment]
Seems to work as expected, now.

**Comment by peek4y** [comment]
Awesome :+1:  thanks!
