### ISSUE TITLE
Access to model in preCreate?

### ISSUE THREAD

**Issue by wesratcliff** [florianholzapfel/express-restify-mongoose#211]
I'm attempting to validate that an application-defined maximum number of records hasn't been reached in the database prior to creating a new record, however, I cannot find an elegant way to know which model is being worked on from within the preCreate (or other) middleware.

*Is there anywhere in the middleware chain where the model is available so that I can run a "model.count()" prior to allowing ERM to insert the record?*

Curious what others have done in this situation. Thank you for the help!

**Comment by Zertz** [comment]
The `model` object is currently not available in pre/post hooks, but I agree that it would be convenient.

Perhaps we could attach it to the req object.

**Comment by wesratcliff** [comment]
Where would be the best spot -- thinking [perhaps here](https://github.com/florianholzapfel/express-restify-mongoose/blob/master/lib/express-restify-mongoose.js#L133) modified to this...

```javascript
app.use(function (req, res, next) {
    req.erm = {}
    req.model = model
    next()
  })
}
```

**Comment by Zertz** [comment]
Yes. Second one

**Comment by wesratcliff** [comment]
Thanks guys!

**Comment by Zertz** [comment]
@wesratcliff Thanks for your contribution!

Also, congrats on (what seems to be) your first PR :)

**Comment by wesratcliff** [comment]
Thanks -- we did #201 as well. Love the library, very well done, appreciate all the work that has been put into it.
