### ISSUE TITLE
Virtual is ignored when creating, 

### ISSUE THREAD

**Issue by sascha1337** [florianholzapfel/express-restify-mongoose#213]
Got this code, after POST create all properties are empty and virtual function NOT executed.
Based on https://github.com/madhums/node-express-mongoose i cant create any user because of this failure. 

```
UserSchema
    .virtual('password')
    .set(function (password) {
        this._password = password;
        this.salt = this.makeSalt();
        this.hashed_password = this.encryptPassword(password);
    })
    .get(function () {
         return this._password;
    });
```

**Comment by Zertz** [comment]
This is because we use `Model.create` internally so Mongoose middleware is not called.

Implementing an option to use the other method of creatnig objects this would fix this issue:

```
var obj = new Model({ ... })
obj.save(...)
```

**Comment by sascha1337** [comment]
where to impletent that ? postCreate ? preCreate ?

secound issue i have is that updating and creating does not apply any user info, just falling back to mongoose 'default' value. PUT with json and POST with json does not work properly even without any mongoose statics/virtuals. No error is coming up, so i dont know what to do exactly :(

**Comment by Zertz** [comment]
You can use `postCreate` for now to run your virtuals.

```javascript
postCreate: function (req, res, next) {
  var obj = req.erm.result

  obj.save(function (err) {
    next(err)
  }
}
```

Mongoose middleware only runs when you set `findOneAndUpdate` to `false`. See [our docs](https://florianholzapfel.github.io/express-restify-mongoose/#findoneandupdate) and [Mongoose docs](http://mongoosejs.com/docs/middleware.html).

**Comment by sascha1337** [comment]
okay thank you very much with this i can go on BUT my big problem now is that working with https://github.com/marmelab/ng-admin is not possible because of the error mentioned before .. so time consuming

**Comment by Zertz** [comment]
It must be something wrong either with the POST/PUT request or something else within your code. Can you show us a sample request?

**Comment by sascha1337** [comment]
tried PUT instead of POST, got this response:

     Request Method:PUT
     Status Code:404 Not Found

when i try POST:
    Request Header:
    Content-Type:application/json;charset=UTF-8

Request Payload:
    {"username":"usernameeee","password":"passssss","userrole":"admin","active":true}

Result is empty object in DB, only default values are set.

**Comment by Zertz** [comment]
You can only update with PUT, not create, hence the 404. If you get 201 back, it should mean the operation succeeded.

1. What version are you on?
2. Does your schema contain those keys?
3. What does the object look like in `postCreate`?

**Comment by sascha1337** [comment]
thank you very much for your support, 

this is the object in postCreate
     { result: { __v: 0, _id: 568aaf9597588cc1138a9c06 },
       statusCode: 201 }

i am using the newest version 2.3.1, my schema looks like this:

    var UserSchema = new Schema({
      username: String,
      password: String,
      userrole: String,
      active: Boolean,
    });

very basic and not working, very annoying :(

**Comment by Zertz** [comment]
Did you set any [private](https://florianholzapfel.github.io/express-restify-mongoose/#private) or [protected](https://florianholzapfel.github.io/express-restify-mongoose/#protected) fields? If so, do you set appropriate [access](https://florianholzapfel.github.io/express-restify-mongoose/#access) on the query?

**Comment by sascha1337** [comment]
no private, no protected fields yet. updated to mongodb version 3.2,  now i have this error on every route:

    code: 9
    errmsg: "Failed to parse: { find: "receivers", filter: {}, skip: "0", limit: "30" }. 'skip' field must be numeric."
    message: "Failed to parse: { find: "receivers", filter: {}, skip: "0", limit: "30" }. 'skip' field must be          numeric."
    name: "MongoError"
    ok: 0
    statusCode: 400
    waitedMS: 0

**Comment by Zertz** [comment]
I am honestly running out of ideas here!

Regarding MongoDB 3.2, we'd have to try and run tests to figure that one out.

**Comment by sascha1337** [comment]
1) Express Read documents limit GET /Customers?limit=1 200:

      Uncaught AssertionError: 400 == 200
      + expected - actual

      -400
      +200
      
      at Request._callback (test/integration/read.js:172:18)
      at Request.self.callback (node_modules/request/request.js:198:22)
      at Request.<anonymous> (node_modules/request/request.js:1035:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:962:12)
      at endReadableNT (_stream_readable.js:905:12)

  2) Express Read documents skip GET /Customers?skip=1 200:

      Uncaught AssertionError: 400 == 200
      + expected - actual

      -400
      +200
      
      at Request._callback (test/integration/read.js:189:18)
      at Request.self.callback (node_modules/request/request.js:198:22)
      at Request.<anonymous> (node_modules/request/request.js:1035:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:962:12)
      at endReadableNT (_stream_readable.js:905:12)

  3) Express limit GET /Customers 200 - override limit in options (query.limit < options.limit):

      Uncaught AssertionError: 400 == 200
      + expected - actual

      -400
      +200
      
      at Request._callback (test/integration/options.js:173:16)
      at Request.self.callback (node_modules/request/request.js:198:22)
      at Request.<anonymous> (node_modules/request/request.js:1035:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:962:12)
      at endReadableNT (_stream_readable.js:905:12)



npm ERR! Test failed.  See above for more details.

**Comment by Zertz** [comment]
Thanks! Can you post this in a separate issue please?

**Comment by sascha1337** [comment]
ok done, lets hope we can find a fix

**Comment by sascha1337** [comment]
ps: empty mongodb objects failure after POST (result 201) bug is still there and kills my productivity

**Comment by Zertz** [comment]
Everything looks fine from what I can gather here. You can try adding a route that matches our create route:

```javascript
router.post('/api/v1/model', function (req, res, next) {
  console.log(req.body)
  next()
})
```

If you can see your data, then you'll have to step through the [POST middleware](https://github.com/florianholzapfel/express-restify-mongoose/blob/master/lib/express-restify-mongoose.js#L147) to figure out where your data gets striped.

If the data isn't there, then something else is wrong.

**Comment by Zertz** [comment]
@sascha1337 Can you try patching the module with the code in PR #219? It should allow your virtuals to run.
