### ISSUE TITLE
distinct can't be use with server limit option

### ISSUE THREAD

**Issue by smirea** [florianholzapfel/express-restify-mongoose#222]
Steps to reproduce:

1. initialize restify with `limit: 20`
1. do a `distinct` query 

An error is thrown: `Error: limit cannot be used with distinct`

This acts the same as doing a `distinct=name&limit=20` query but these 2 situations are notably different. The server option limit should not apply to `distinct` queries

**Comment by Zertz** [comment]
Interesting, thanks for reporting this!
