### ISSUE TITLE
Restrict populate of referenced objects to only certain fields.

### ISSUE THREAD

**Issue by ravishivt** [florianholzapfel/express-restify-mongoose#225]
Let's say I have two models with two corresponding API routes, one for users and one for articles.

userSchema = new mongoose.Schema({
  email: String,
  firstName: String,
  lastName: String
});
var Users = mongoose.model('User', userSchema);

articleSchema = new mongoose.Schema({
  title: String,
  description: String,
  createdBy: {type: mongoose.Schema.Types.ObjectId, ref: 'User'},
});
var Articles = mongoose.model('Article', articleSchema);

My goal is to hide the email address in all API queries as this is personal information.  I can do this easily in the Users API by making "email" a private field.  The problem is if I query the Article API and populate on "createdBy", the full user object is embedded within.  The workaround I've found is to manipulate req._ermQueryOptions.populate variable in preMiddleware to ensure that all populate paths have a select property set to only the properties I want returned, e.g. ```req._ermQueryOptions.populate = [{"path": "createdBy", "select": "firstName lastName"}]```

Coming from a Django + django-rest-framework background, they accomplish the goal by using a [Serializer](http://www.django-rest-framework.org/api-guide/serializers/) class for all API objects, including references to other models.  That way, the serializer uniformly enforces which fields are read-only.

**Comment by Zertz** [comment]
Thanks for letting us know, this should not happen. I'm pretty sure we have tests that are supposed to cover this use case.

Can you try the code in the `refactor-resource-filter` branch and see if it exhibits the same issue?

**Comment by ravishivt** [comment]
"I've made a huge mistake."  I was actually doing some custom logic in outputFn to filter out restricted fields instead of using the private/protected/public options.  I was not aware those options would work for populated references as well.  After testing the "private" feature, I can confirm that it does indeed keep those fields filtered out in populated references.  Awesome!  (and sorry)

**Comment by Zertz** [comment]
Great, no worries!
