### ISSUE TITLE
KOA Support

### ISSUE THREAD

**Issue by LucianoGanga** [florianholzapfel/express-restify-mongoose#226]
Hi! 

I've been using this module in an express server. Now, I'm making a new app using KOA, but I'll like to keep using this.
Is it possible to find an easy way to implement this module in KOA? 

I know that the name is `express-restify-mongoose`, but maybe someone here already made the solution. 

I found this [https://github.com/pixel2/koa-restify-mongoose](https://github.com/pixel2/koa-restify-mongoose) repo, but it's not very updated. 

Thanks!

**Comment by Zertz** [comment]
I am not familiar with Koa, but if there's a straightforward way to support it, I am open to a PR and I'm sure @florianholzapfel would be as well.

**Comment by Zertz** [comment]
Also, this project has been updated since that fork, but it's mostly refactoring. The core is very similar.

**Comment by LucianoGanga** [comment]
Thanks @Zertz . I'll be checking this next week (I have to finish some tasks first), and if I can make any change to support it straightforward, I'll be posting here again with a PR. 
Meanwhile, if someone has any idea on what things I have to keep in mind to do this, that will be awesome.

**Comment by LucianoGanga** [comment]
@Zertz, @florianholzapfel , I made my own repository with the KOA support. The thing is that I had to rewrite all the middlewares and all the parts of the code that used express, so I couldn't do a fork and I just cloned it.
This is the URL: [https://github.com/LucianoGanga/koa-restify-mongoose](https://github.com/LucianoGanga/koa-restify-mongoose)

I need it for my project, so I'd like to make it an npm module and publish it. 

If you guys allow me to do that, I'd really appreciate it. Besides that, of course I'd put a reference to your repository. 

About the functionality, I had to remove the private fields functionality, and a postMiddleware. 

The code is not as tidy as I'd like right now, but I'll like to arrange it better in the next weeks. The thing is that I need it now for my project, so I was in a rush to finish it. 

I'll be waiting for your answer to publish the npm module if you let me. 

Thanks!
Luciano

**Comment by Zertz** [comment]
Good work! I like what you've done with **normalizeMiddleware**, cleans up the main file nicely. Just a suggestion, you should probably run our tests against your code to make sure no bugs were introduced.

It's [MIT licensed](https://github.com/florianholzapfel/express-restify-mongoose/blob/master/LICENSE) so you are free to "use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software". Attribution is of course appreciated :)

**Comment by LucianoGanga** [comment]
Nice! Thanks you Zertz!

I just couldn't let the code to be messy like that and now I'm trying to do the things right with a fork from your repo. It's quite hard for me because it's my first time doing this, but I'll try the best :) 

Also, I'll be integrating the tests soon, and babel, like you have in your code, as we share a few files and I don't want to loose your upgrades (maybe I can merge a few files of you when you update them)

I'll let you know here when I finish this, so other people can use this too. 

Thanks!
Luciano

**Comment by Zertz** [comment]
Awesome! It's great to have new people in open source :)

I would recommend you fork this repository and modify that instead of making a new one from scratch. This would make your life easier if you want to keep up to date with the changes in this repo.

**Comment by LucianoGanga** [comment]
Here it is! 
GitHub: [https://github.com/LucianoGanga/koa-restify-mongoose](https://github.com/LucianoGanga/koa-restify-mongoose)

NPM: [https://www.npmjs.com/package/koa-restify-mongoose](https://www.npmjs.com/package/koa-restify-mongoose)

I have to test it more now, but it should work the same way than yours. I added the access functionality for fields too, so the only thing missing is the postMiddleware and adapt the test and examples to KOA. I'll do it when I have the time. 

Thanks @Zertz !

**Comment by Zertz** [comment]
You're welcome, let us know if you have questions related to the code

**Comment by florianholzapfel** [comment]
@LucianoGanga Great work!

**Comment by LucianoGanga** [comment]
Thanks @florianholzapfel !

@Zertz , now that you mention, I do have a question. Why did you remove the "plural" functionality in the code? 

Cheers!

**Comment by Zertz** [comment]
See #234 and inflection is limited to English
