### ISSUE TITLE
Typo in the docs.

### ISSUE THREAD

**Issue by svbatalov** [florianholzapfel/express-restify-mongoose#228]
Sample code for various middleware functions (involving `performAsyncLogic`) in the [documentation](https://florianholzapfel.github.io/express-restify-mongoose/) is mising closing parenthesis
```
preMiddleware: function (req, res, next) {
  performAsyncLogic(function (err) {
    next(err)
  } // <= Need parenthesis here
}
```

**Comment by Zertz** [comment]
Good catch, thanks!

Would you mind submitting a PR? Documentation is in the [gh-pages](https://github.com/florianholzapfel/express-restify-mongoose/blob/gh-pages/index.md) branch.

**Comment by svbatalov** [comment]
Done: #229
