### ISSUE TITLE
Name of collection as parameter adds an 'S' to the end of the name

### ISSUE THREAD

**Issue by Quixomatic** [florianholzapfel/express-restify-mongoose#232]
For example:

restify.serve(router, mongoose.model('core_dictionary', new mongoose.Schema({
	...............................
})));

Would require api/v1/core_dictionarys. This would be fine if it looked for core_dictionary as the collection and just used core_dictionarys as the route, that that is not the case.

This forces a naming convention I do not want to use onto my collections, why can't we choose our own names without making them plural.

**Comment by Zertz** [comment]
You can use [`plural: false `](https://florianholzapfel.github.io/express-restify-mongoose/#plural)

**Comment by Quixomatic** [comment]
Thank you for your quick response, after looking at the documentation I can see I need to add that as an option within the parameters. Not sure what the particular syntax should look like, can you provide a very basic example showing plural: false in the .serve parameters?

**Comment by Zertz** [comment]
```js
restify.serve(router, model, {
  plural: false,
  ...
}
```

**Comment by Quixomatic** [comment]
thanks so much.

**Comment by Quixomatic** [comment]
This gives me [] in the response for a GET request. The name of my collection is definitely 'core_table'

When the plural option is removed and the name of the model is 'core_tables' AND I set the name of the collection in my database to 'core_tables' the GET request works.

restify.serve(app, mongoose.model('core_table', new mongoose.Schema({
	update_count: { type: String, required: false },
	created_date: { type: String, required: false },
	created_by: { type: String, required: false },
	updated_date: { type: String, required: false },
	updated_by: { type: String, required: false },
	table_name: { type: String, required: true },
	table_label: { type: String, required: true },
	display_field_name: { type: String, required: false }
})), { plural: false });

**Comment by Zertz** [comment]
Unless you specify a collection name, mongoose will pluralize the collection's name according to the model's name. So if you define `mongoose.model('core_table', schema)`, the collection will be called `core_tables`. Ultimately, this doesn't matter because it's mongoose handling it internally.

As for our side of the implementation, we grab the model's name, `core_table`, and pluralize the endpoint or not, according to the `plural` setting.

```js
restify.serve(router, mongoose.model('core_table', schema), {
  plural: false
}

// GET /api/v1/core_table
// Response: 200 OK
// Content: []

// GET /api/v1/core_tables
// Response: 404 Not Found
```

`[]` means the request was completed successfully, it's returning you an empty array.

**Comment by Quixomatic** [comment]
Thank you for clearing that up, setting this to closed.

**Comment by duard** [comment]
when I put the plural setting, my server show this error : 

```
Error: collection name must be a String
```

restify.serve(router, mongoose.model('ibge', ibge,{plural: false}));

**Comment by Zertz** [comment]
There's a small mistake in your code:

```
restify.serve(router, mongoose.model('ibge', ibge), {
  plural: false
});
```
