### ISSUE TITLE
Is there a way to manually perform a PATCH from within some middleware?

### ISSUE THREAD

**Issue by Quixomatic** [florianholzapfel/express-restify-mongoose#244]
I would like to write some middleware, probably preCreate or postCreate, that will update some data in another collection. Is there anything I can do to access and perform a PATCH on a specific document from within middleware?

**Comment by Zertz** [comment]
Yes, you can do anything within middleware. Simply use [request](https://www.npmjs.com/package/request) to query your API.

```js
var request = require('request')

restify.serve(router, model, {
  preCreate: function (req, res, next) {
    request.patch(url, {
      // data
    }, function (err, res, body) {
      next()
    })
  }
})
```

**Comment by Quixomatic** [comment]
Oh wow, that will make things a lot easier, any chance for this to be added to the documentation?

**Comment by Zertz** [comment]
Good!

There is a generic [example](https://florianholzapfel.github.io/express-restify-mongoose/#precreate), perhaps we could improve the code in `examples/` and move it to the docs to have a complete example or even  create a Yeoman generator.

**Comment by Quixomatic** [comment]
request.patch is undefined, is it part of your library?

**Comment by Quixomatic** [comment]
Ignore that, just saw you gave me a link to the docs

**Comment by Quixomatic** [comment]
This patch does not seem to be doing anything:

```
      request.patch('/api/v1/core_schema/' + tempDocs[0]._id, data, function (err, res, body) {
        next(err);
      });
```

When I run the same patch in postman3.0 it works fine and updates the schema_data field on my document. I checked the _id to make sure it matches and it does. Just cant figure out why this doesn't work.

Below is part of how I create the updated schema_data to be stored in the collection 'core_schema'

```
      temp_schema_data[req.body.field_name] = {
        type : req.body.field_type,
        required : req.body.required
      };
      
      var data = {
        "schema_data" : temp_schema_data
      }
```

**Comment by Quixomatic** [comment]
Any thoughts on creating a yeoman generator to kind of follow with the documentation? I understand pretty much everything about how this library works now, but I still think it would be extremely useful.

**Comment by Zertz** [comment]
It is something that has crossed my mind, unfortunately time is a bit of an issue. It would be great if someone were to contribute such a generator though :)
