### ISSUE TITLE
basic usage

### ISSUE THREAD

**Issue by alfredopacino** [florianholzapfel/express-restify-mongoose#247]
I'm sorry for the newbie question, but since your basic example shows a single file usage, I'm having troubling figuring out how to separate the code in MVC and what exports in node environment.
This is my model
/models/customer.js
```
var express = require('express')
var bodyParser = require('body-parser')
var methodOverride = require('method-override')
var mongoose = require('mongoose')
var restify = require('express-restify-mongoose')
var app = express()
var router = express.Router()

app.use(bodyParser.json())
app.use(methodOverride())

restify.serve(router, mongoose.model('Customer', new mongoose.Schema({
    name: { type: String, required: true },
    comment: { type: String }
})))
app.use(router)

```

but the http server is created in bin/www
and the main nodejs script is /app.js
(i'm using express-generator for the skeleton)

since the resources aren't exposed at all,
/api/v1/Customers returns 404.

**Comment by florianholzapfel** [comment]
You should do something like this:

/models/customer.js
```
module.exports = mongoose.model('Customer', new mongoose.Schema({
    name: { type: String, required: true },
    comment: { type: String }
}))
```

/app.js
```
var express = require('express')
var bodyParser = require('body-parser')
var methodOverride = require('method-override')
var mongoose = require('mongoose')
var restify = require('express-restify-mongoose')
var app = express()
var router = express.Router()

var customer = require('./models/customer')

app.use(bodyParser.json())
app.use(methodOverride())

restify.serve(router, customer)
app.use(router)
```

**Comment by alfredopacino** [comment]
Very thanks, but do you tested this in an express-generator project?
I get still 404..

**Comment by florianholzapfel** [comment]
I have tested this, but I forgot to mention that the url needs to be ```/api/v1/Customer```

**Comment by alfredopacino** [comment]
yeah I knew that :)
I will do further investigations
