### ISSUE TITLE
model name pluralization in the docs

### ISSUE THREAD

**Issue by joshcartme** [florianholzapfel/express-restify-mongoose#248]
Here, https://florianholzapfel.github.io/express-restify-mongoose/#express-4-app, it says that you will generate endpoints like:

```
GET http://localhost/api/v1/Customers
PUT http://localhost/api/v1/Customers
POST http://localhost/api/v1/Customers
DELETE http://localhost/api/v1/Customers
```

but none of those should be pluralized since the model name is `Customer` and `options.name` is not specified.  The old behavior was to pluralize by default so I think this is a result of that

**Comment by alfredopacino** [comment]
I'm not a contributor of this module but I can tell the Restful 'contract' uses the plural.

**Comment by joshcartme** [comment]
@alfredopacino the plural option was [removed](https://github.com/florianholzapfel/express-restify-mongoose/blob/master/CHANGELOG.md#300) as of version 3.  I think the docs just haven't been updated to reflect that yet as `{plural: true}` used to be the default and the way this changes endpoints by default

**Comment by Zertz** [comment]
@joshcartme You are correct! I missed that when I updated the docs.

If you want to PR, the docs are on the gh-pages branch and the mistake is in the root index.md

**Comment by alfredopacino** [comment]
@joshcartme well maybe it could be confusing the model in singular and the resource in plural (maybe) but as I said REST standards prefer the plural
http://www.restapitutorial.com/lessons/restfulresourcenaming.html
so now there is no way to have the resource in plural but explicitly define the name of the resource in options?

**Comment by florianholzapfel** [comment]
You can use ```restify.serve(model, { name: require('inflection').pluralize(model.modelName).toLowerCase() })``` to generate a plural name.

**Comment by Zertz** [comment]
Documentation has been updated :+1:

**Comment by alfredopacino** [comment]
@florianholzapfel I'm searching for a way to set once the options for all the resources. I can't use model.modelName.

**Comment by florianholzapfel** [comment]
Documentation can be found here: https://florianholzapfel.github.io/express-restify-mongoose/

You can use ```restify.defaults(options)``` to set default options

Why can't you use ```model.modelName```?

**Comment by alfredopacino** [comment]
in docs I can see nothing about pluralization..

**Comment by joshcartme** [comment]
@zertz thanks! If notice anything else (probably  won't, its working great) I'll definitely submit a PR.
