### ISSUE TITLE
populate all refs

### ISSUE THREAD

**Issue by alfredopacino** [florianholzapfel/express-restify-mongoose#249]
Hi, I have several refs in my docs, there is a way to populate all without explicit list?

This is my sample schema: refs, array of refs and even array of embedded document with refs in it.

```
var mySchema = new Schema({
    name:{type:String,description:"Title"},
    ref:{type: ObjectId, ref: 'mod0' },
    array:[{type: ObjectId, ref: 'mod1' }],
    embedded:[{ref:{type: ObjectId, ref: 'mod2' },comment:String}]
...
}

```

**Comment by Zertz** [comment]
We mirror mongoose behavior so you must call populate with all the fields you need.

**Comment by alfredopacino** [comment]
not sure how can I do that since the resource are exposed automatically..

**Comment by Zertz** [comment]
You can use middleware to do that.

```js
{
  preDelete: function (req, res, next) {
    res.sendStatus(403)
  }
}
```

**Comment by Zertz** [comment]
All fields must be manually populated :

`GET /Model?populate="field1,field2,field3"`
