### ISSUE TITLE
Model names are not pluralized in v3

### ISSUE THREAD

**Issue by svbatalov** [florianholzapfel/express-restify-mongoose#256]
Hi.
In v2 model names were pluralized automatically, while in v3  it seems they are not and corresponding option is missing. What is the supposed behaviour? Documentation is not clear on this, as there are both `Customer` and `Customers` in examples.

**Comment by Zertz** [comment]
Indeed, this was changed in 3.0 to fix a consistency issue when combining certain options. It is documented in the [changelog](https://github.com/florianholzapfel/express-restify-mongoose/blob/master/CHANGELOG.md#300).

Some examples may have slipped through, which are you refering to?

**Comment by svbatalov** [comment]
Please take a look at PR a47d896.

**Comment by Zertz** [comment]
:heart:
