### ISSUE TITLE
Broadcasting of PUT/POST/DELETE operations via websockets

### ISSUE THREAD

**Issue by OliverFischer** [florianholzapfel/express-restify-mongoose#274]
Hi Florian,
for some models (especially some models in certain contexts, we like to broadcast the changes of the model instances after successful save/update/delete ops in mongoose to all clients connected to the app).  Any idea of an approach to achieve this?

**Comment by wesratcliff** [comment]
I'm doing something similar by using a modified version of [mongoose-eventify](https://github.com/Moveline/mongoose-eventify) that sends jobs off to a worker queue where they are picked up and distributed to clients.

The ERM post middleware or postProcess could also be used as a convenient hook.

**Comment by Zertz** [comment]
Yep, each operation has its [post middleware](https://florianholzapfel.github.io/express-restify-mongoose/#postcreate) so you can use that!

**Comment by OliverFischer** [comment]
Thank you guys, that was all I needed to know. @wesratcliff :+1:

**Comment by OliverFischer** [comment]
Hi all, I ended by using a slightly modified version of mongoose-eventify using an app-wide [pattern-emitter](https://github.com/danielstjules/pattern-emitter) to connect socket-io with the mongoose hooks  for (pre,post save/remove) to make the functionality outside of erm. Instructed erm not to use findOneAndRemove and findOneAndUpdate.  Thanks again for pointing me in the right direction,
