### ISSUE TITLE
Projection with exclusions and Populate

### ISSUE THREAD

**Issue by kranthi561** [florianholzapfel/express-restify-mongoose#277]
I'm getting an error: 

> MongoError: Can't canonicalize query: BadValue Projection cannot have a mix of inclusion and exclusion.

when I'm passing below query: 
```
Resource.get({
            id: id,
            populate: 'program',
            select: {
                act: 0,
                acc: 0
            }
        }, cb);
```

How do we use select exclusions and Populate together?

**Comment by Zertz** [comment]
This error is coming from MongoDB directly, I think because using populate with Mongoose adds an implicit `program: 1` to your selected fields.

What happens if you run this instead:

```js
Resource.get({
  id: id,
  populate: 'program',
}, cb);
```

**Comment by kranthi561** [comment]
It is working fine without exclusions but, I want exclude some fields.
Is there any alternative way to using exclusions?

**Comment by Zertz** [comment]
If you also want to populate then you have to do it the other way around. Specify the fields you want, including the field you are populating.

**Comment by kranthi561** [comment]
Thank you.
