### ISSUE TITLE
View all generated endpoints

### ISSUE THREAD

**Issue by KholofeloMoyaba** [florianholzapfel/express-restify-mongoose#278]
Can I view all generated endpoints?
I'm currently getting a 404 when I try using one of the routes that I think should exist.

**Comment by Zertz** [comment]
*Sort of.*

```js
const uri = restify.serve(Model, router, { ... })

// uri = '/api/v1/Model'
```

**Comment by KholofeloMoyaba** [comment]
Thanks @Zertz,
However I want a list of all the possible routes generated e.g:
```
GET http://localhost/api/v1/Model/count
GET http://localhost/api/v1/Model
POST http://localhost/api/v1/Model
DELETE http://localhost/api/v1/Model
GET http://localhost/api/v1/Model/:id
PUT http://localhost/api/v1/Model/:id
POST http://localhost/api/v1/Model/:id
DELETE http://localhost/api/v1/Model/:id
```

This will help to know exactly which routes are active - also can help with generating documentation.

**Comment by Zertz** [comment]
The complete list of generated endpoints is in the [documentation](https://florianholzapfel.github.io/express-restify-mongoose/#express-4-app).

You can use the method I outlined above to find the base URI, but it is unfortunately not possible for the library to know which are "active" since the user can customize everything with middleware.

Do you suggest `restify.serve()` should return some sort of map of all possible endpoints rather than just the base URI?

**Comment by KholofeloMoyaba** [comment]
Well, that's not really what I had in mind. It makes sense that it returns the base.
What I was thinking of was more of a utility function which given, what schema, you used, and what options you used in `resitfy.serve()` you can get an array of all methods for example:
```
paths = resitify.getPossibleEndPoints(schema,options);
```

where paths will look like:
```
[ {"method":"GET", url:"/User/:id"}, 
  {"method":"POST",url:"/User"},
...
]
```

However, now that I think about it, this is more of a nice to have than a real necessity. But it can help for validation.

**Comment by Zertz** [comment]
Interesting, I'll keep that in mind.

Did you solve the issue you were having?

**Comment by KholofeloMoyaba** [comment]
Yes,
I was updating a system which had been using v0.7. The endpoints generated were pluralised i.e. `/users/:id` as opposed to `/User/:id` for schema `User`.
Sweet.
I was wondering why suddenly all requests were giving me a 404 Error.
The quick solution was to use `options.name` to put the custom pluralised name.
In time it would be worthwhile to change the referenced urls to use the original non-pluralised schema model-name as the base, it is more RESTful that way.

So in this case, if the method I was talking about was available, it would have been easy to see that the endpoints that were being called didn't exist because they were named differently. Instead I had to do a lot of digging to find the issue.

**Comment by Zertz** [comment]
Glad you got it fixed!

Pluralisation was removed in 3.0, it is in the changelog. However, the value returned by `serve` may not be documented, I'll leave this open as a reminder.

**Comment by Zertz** [comment]
This is now documented [here](https://florianholzapfel.github.io/express-restify-mongoose/#reference).
