### ISSUE TITLE
non-string populate.select throws uncatchable error:

### ISSUE THREAD

**Issue by smirea** [florianholzapfel/express-restify-mongoose#281]
doing the following query: `/User?populate={"path":"father", "select":["name", "age"]}` 
(`select` is an array which is invalid format)

throws the following error: `TypeError: Invalid select() argument. Must be string or object.`

That error cannot be caught as it does not trigger `options.onError` neither the generic express `app.use((req, res, next, error) => {})` middleware and it instantly kills the api server

**Comment by Zertz** [comment]
This is most likely because [JSON.parse exceptions](https://github.com/florianholzapfel/express-restify-mongoose/blob/master/src/middleware/prepareQuery.js#L116) on certain query parameters assume that it failed because the parameter is a string. However, the error should still be caught and passed to `onError`.

Can you provide a stack trace to see exactly where this error is being thrown?

**Comment by smirea** [comment]
here's the stack trace:

```
TypeError: Invalid select() argument. Must be string or object.
    at Query.select (__project__/node_modules/mquery/lib/mquery.js:1100:9)
    at Function.find (__project__/node_modules/mongoose/lib/model.js:1148:6)
    at populate (__project__/node_modules/mongoose/lib/model.js:2646:15)
    at _populate (__project__/node_modules/mongoose/lib/model.js:2470:5)
    at Function.Model.populate (__project__/node_modules/mongoose/lib/model.js:2427:5)
    at Immediate.cb (__project__/node_modules/mongoose/lib/query.js:1046:17)
    at Immediate._onImmediate (__project__/node_modules/mquery/lib/utils.js:137:16)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by Zertz** [comment]
Thank you!

I believe it is crashing [here](https://github.com/florianholzapfel/express-restify-mongoose/blob/master/src/buildQuery.js#L32) and there would probably be a similar error for `populate` and perhaps `sort`. I wasn't aware these methods could throw, neither does it seem to be [documented](http://mongoosejs.com/docs/api.html#query_Query-select).

We should put together some tests first, but the fix should be straightforward.

**Comment by Zertz** [comment]
@smirea Can you try updating your dependency to the code in #282?

```js
dependencies: {
  "express-restify-mongoose": "florianholzapfel/express-restify-mongoose#63892e4"
}
```

**Comment by smirea** [comment]
that looks good to me
