### ISSUE TITLE
[question] Accessing 'req' object in a mongoose middleware

### ISSUE THREAD

**Issue by filipows** [florianholzapfel/express-restify-mongoose#283]
Can I somehow add `req.user._id` to document before saving it.

Something like:
```javascript
schema.pre('save', function (next) {
  this.createdBy = req.user._id;   // is it possible to access req here?
  next()
})
```
Do you know if it is possible to achieve something like that?

**Comment by Zertz** [comment]
Mongoose middleware doesn't have access to the request object, it is also a separate project for which you can find documentation in their [repository](https://github.com/Automattic/mongoose).

What you can do, is use our [preCreate](https://florianholzapfel.github.io/express-restify-mongoose/#precreate) middleware.

```js
restify.serve(router, model, {
  preCreate: function (req, res, next) {
    req.body.createdBy = req.user._id
    next()
  }
})
```

**Comment by filipows** [comment]
Hey @Zertz ,
thanks for your reply.

I cannot find it in Mongoose docs, but I found [this](http://stackoverflow.com/questions/10485302/node-mongoose-getting-to-request-context-in-mongoose-middleware) and [this](https://github.com/Automattic/mongoose/issues/499) which shows that it's possible to pass an argument to `.save()` method as follow:
```javascript
var item = new Item();
item.save(req, function() {  });
```
and then access it in `pre save hook`:
```javascript
item.pre('save', function (next, req, callback) {
  console.log(req);
  next(callback);
});
```

Maybe it's worth considering to use `.save` method on document, rather than `.create` as it's presented [here](http://mongoosejs.com/docs/models.html)? 
What do you think?

**Comment by Zertz** [comment]
My highly opiniated view on this is that you should not use `req` in your models as it couples your database with your web framework so I would recommend using the method I outlined above.

That said, we could investigate passing `req` into save. However, I'm curious as to what happens in the case of async middleware.

**Comment by filipows** [comment]
Ok, it seems reasonable for me (at least for now ;) ).
Thank you for your time!

**Comment by Rahul-Geeks** [comment]
> Hey @Zertz ,
> thanks for your reply.
> 
> I cannot find it in Mongoose docs, but I found [this](http://stackoverflow.com/questions/10485302/node-mongoose-getting-to-request-context-in-mongoose-middleware) and [this](https://github.com/Automattic/mongoose/issues/499) which shows that it's possible to pass an argument to `.save()` method as follow:
> 
> ```js
> var item = new Item();
> item.save(req, function() {  });
> ```
> 
> and then access it in `pre save hook`:
> 
> ```js
> item.pre('save', function (next, req, callback) {
>   console.log(req);
>   next(callback);
> });
> ```
> 
> Maybe it's worth considering to use `.save` method on document, rather than `.create` as it's presented [here](http://mongoosejs.com/docs/models.html)?
> What do you think?

This solution works with pre-hook but not with post-hook. On passing argument in `.save()`, the post hook does not even get called.
So, do you have any idea about how we can access request object(or any other object) in post hook.
