### ISSUE TITLE
aggregation command

### ISSUE THREAD

**Issue by m-menon** [florianholzapfel/express-restify-mongoose#287]
hi,

Thanks for the excellent lib. Just a simple question - can I run any mongo commands...say things like aggregation framework operators like `db.myCollection.aggregate(` using this?

Cheers,
M.M

**Comment by gDelgado14** [comment]
Caveat: I just started looking into this lib today but by the looks of it, yes you can do aggregates.

if, for example you do `GET http://localhost/api/v1/Customer/__SOME__ID__` then the [getItem](https://github.com/florianholzapfel/express-restify-mongoose/blob/master/src/operations.js#L91) middleware is invoked, which checks to see if you specified a [contextFilter](https://florianholzapfel.github.io/express-restify-mongoose/#contextfilter) ... 

What you can do inside the `contextFilter` is something like the following: 

```javascript
restify.serve(api, Inventory, {
  contextFilter: (model, req, done) => {
    model.aggregate([
      // magic!!!!
    ]).then(done)  // make sure you invoke done or express will not be happy that you did that! 
  }
})
```

**Comment by gDelgado14** [comment]
Actually looks like you can't perform aggregates. 

contextFilter is expected to return a `filteredContext` with a `findOne` method. See **[here](https://github.com/florianholzapfel/express-restify-mongoose/blob/master/src/operations.js#L9)**

**Comment by Zertz** [comment]
You can perform any async operation (including aggregates) using the various hooks, but the lib itself does not have built-in support.

```js
restify.serve(api, Inventory, {
  contextFilter: (model, req, done) => {
    model.aggregate([
      // magic!!!!
    ]).then(() => {
      done(model.find())
    })  // make sure you invoke done or express will not be happy that you did that! 
  }
})
```
