### ISSUE TITLE
[Bug] Shared access when same field name

### ISSUE THREAD

**Issue by Pierre-Demessence** [florianholzapfel/express-restify-mongoose#288]
Hello,
I found a behavior that looks like a bug where fields that share the same name accross different schema also share the same access policy :

### Context :
```js
// First Schema with private access on the "name" field.
var SchemaA = new mongoose.Schema({
  name: {
    type: String,
    access: 'private'
  }
}

// Second Schema with no private access on the "name" field.
var SchemaB = new mongoose.Schema({
  name: {
    type: String
  }
}
```

### Behavior/Bug :
If you do a GET request on A you'll not get the `name` field.
**But if you do a GET request on B you'll not get the `name` field either.**
_(The same would be for any other schema with a `name` field)_

Adding public access on `SchemaB.name` field won't do anything.
```js
var SchemaB = new mongoose.Schema({
  name: {
    type: String,
    access: 'public' // this doesn't change the bevahior
  }
}
```

### Workaround :
The weirdest thing here is that adding private access in the `restify.serve()` options of A will fix the issue :
```js
restify.serve(router, ModelA, {
  private: ['name']
});
```
Now `SchemaA.name` is private but `SchemaB.name` is public !
On top of that, adding `  private: ['name']` will not only make `SchemaB.name` public **but also any other field that would be private because of a shared name**.

&nbsp;

Do you have any idea on what could be causing this ?
Is this a mongoDB behavior of sharing field properties when the name is similar ?
Is this a bug withing this lib ?
Or is this maybe the intended behavior ?

**Comment by Zertz** [comment]
Looks like a bug, would have to write some tests to confirm. Thanks for reporting!

**Comment by fdelayen** [comment]
Hello,

I just tested that and it looks like it's working as expected with this code and versions : 
```
"dependencies": {
    "body-parser": "^1.15.2",
    "express": "^4.14.0",
    "express-restify-mongoose": "^4.1.1",
    "method-override": "^2.3.6",
    "mongoose": "^4.6.0"
 }
```

```JavaScript
const express = require('express')
const bodyParser = require('body-parser')
const methodOverride = require('method-override')
const mongoose = require('mongoose')
const restify = require('../express-restify-mongoose/src/express-restify-mongoose')
const app = express()
const router = express.Router()

app.use(bodyParser.json())
app.use(methodOverride())

mongoose.connect('mongodb://localhost:27017/erm')
mongoose.Promise = Promise;

restify.serve(router, mongoose.model('A', new mongoose.Schema({
  name: { type: String, required: true },
  type: { type: String, access: 'private'  }
})))

restify.serve(router, mongoose.model('B', new mongoose.Schema({
  name: { type: String, required: true },
  type: { type: String  }
})))

app.use(router)

app.listen(3000, () => {
  console.log('Express server listening on port 3000')
})

```

Type in A is private, but type in B is not.
Is this issue resolved for you ? Can you provide a complete non-working example ?

**Comment by Pierre-Demessence** [comment]
After a long search I may have found the culprit :

By adding `restify.defaults({})` (with or without data in the object) **before** the several `restify.serve()`, the behavior occurs and you don't get `type` for B.
I tested it with the same code and versions.

If put after the `restify.serve()` we don't get the same behavior but it's expected as the doc state :
> sets this object as the defaults for anything served **afterwards**
