### ISSUE TITLE
distinct query with totalCountHeader=true fails silently

### ISSUE THREAD

**Issue by maozedong** [florianholzapfel/express-restify-mongoose#289]
Steps to reproduce
   initialize restify with totalCountHeader: true
   do a distinct query
Result
no response generated
no errors emitted

seems that following code will suppress mongo errors, it lacks a catch block at the end
operations.js: line 36
`query.lean(options.lean).exec().then(function (items) {
        ...
      }, errorHandler(req, res, next));`

**Comment by Zertz** [comment]
Thanks for reporting this! Also, it seems like the last couple commits are not actually published. I will try to do a release this week.

mpromise (mongoose's built in promise library) isn't a complete Promise implementation. The second argument to `.then()` is the error handler, which is also the case in the full Promises/A+ specification, but it has slightly different semantics IIRC.
