### ISSUE TITLE
Populate populated field? 

### ISSUE THREAD

**Issue by LucianoGanga** [florianholzapfel/express-restify-mongoose#290]
Hi! 
Is it possible to populate a populated field? 

In my case, I have this: 

Making a request like: `GET /rest/users` gives me
```js

{
	_id: "56a66171700181781dc5c4c2",
	name: "Marcos",
	group: "57278c235519a1030035a70f"
}
```

Making a request like: `GET /rest/users?populate=group` gives me
```js

{
	_id: "56a66171700181781dc5c4c2",
	name: "Marcos",
	group: {
		_id: "57278c235519a1030035a70f",
		parent: "56a66b5cd4c609bb064d11ba",
		ancestors: [
			"56a664bcd4c609bb064d11a8",
			"56a66b5cd4c609bb064d11ba"
		]
	}
}

```

And what I need, is something like this: `GET /rest/users?populate=group,group.ancestors` 
```js

{
	_id: "56a66171700181781dc5c4c2",
	name: "Marcos",
	group: {
		_id: "57278c235519a1030035a70f",
		parent: "56a66b5cd4c609bb064d11ba",
		ancestors: [


			{
				_id: "56a664bcd4c609bb064d11a8",
				parent: "56a66b5cd4c609bb064d11ba",
				ancestors: [
					"56a66b5cd4c609bb064d11ba"
				]
			},
			

			{
				_id: "56a66b5cd4c609bb064d11ba",
				parent: "56a66b5cd4c609bb064d11ba",
				ancestors: []
			}
		]
	}
}

```

Is there any way to do all that in the same request? 

Thanks!
Luciano

**Comment by Zertz** [comment]
This is unfortunately not possible. Using mongoose, you would have to run the following code,

```js
Model.find().populate('group').exec().then((items) => {
  return items.populate('group.ancestors').execPopulate()
}).then((items) => {
  // We had to run two mongoose queries to get here
})
```

Also, note that even a single call to `.populate()` actually runs a second query as there is no join operation in MongoDB. This is why you generally want to favor flatter documents rather than nested relationships.

**Comment by Zertz** [comment]
I hadn't thought of this at the time, but here's what you *can* do.

```js
restify.serve(router, model, {
  postRead: function (req, res, next) {
    req.erm.result.populate('group.ancestors').execPopulate().then((result) => {
      // req.erm.result is now fully populated
      next()
    }).catch(next)
  }
})
```

**Comment by 95deepan** [comment]
It worked for me this way:

api/v1/banners?populate=[{"path":"products","populate": [{ "path":"colors" }] }]

Hope it helps 😃
