### ISSUE TITLE
Alter response body when using preRead or postRead middleware

### ISSUE THREAD

**Issue by Quixomatic** [florianholzapfel/express-restify-mongoose#293]
Is there a way to access the response body and change it or add things to it with preRead/postRead middleware? I can see req.erm.result, but can't modify it from what I can see.

**Comment by Quixomatic** [comment]
Also just want to say I've been using this framework for some time now on a few different projects and it is a lifesaver!

**Comment by Zertz** [comment]
Thank you for saying that, it is very much appreciated. I'll get back to you with a proper answer :-)

**Comment by Zertz** [comment]
You should be able to modify `req.erm.result` in post middleware, call `next` and see your changes reflected in the response. Is that not working for you?

**Comment by Zertz** [comment]
@Quixomatic Since this should work out of the box, have you been able to find the issue you were having?

I will close this for now, feel free to re-open if there still is a problem :-)
