### ISSUE TITLE
[advice] Maybe we can change the fixed `private/protected` fields with dynamic `select`...

### ISSUE THREAD

**Issue by xialvjun** [florianholzapfel/express-restify-mongoose#299]
Just like the `contextFilter` will do one more filter on the filtered data,  we can make a `contextSelector` to do a select on the returned data... That's much more flexible than fixed `private/protected` fields.

```
contextSelector: function (query, req, done) {
  if (req.user.isAdmin) {
    done(query)
  } else {
    done(query.select('filedOne filedTwo'))
  }
}
```

**Comment by Zertz** [comment]
Agreed! I've looked at a few different options and I like your suggestion a lot! At a glance, it seems relatively simple to implement and even a non breaking change. The only thing we would have to watch for is the interaction with `private` and `protected` fields, I'm thinking perhaps a simple `throw` when both options are present. Would that work for you?

**Comment by xialvjun** [comment]
Yeah, hope to see it soon...😁
