### ISSUE TITLE
centerSphere Query 

### ISSUE THREAD

**Issue by candoucreative** [florianholzapfel/express-restify-mongoose#304]
I built a dating app using this product its awesome and easy to work with it,  i have quick question if anyone else tried such a query like this to use the mongodb centerSphere i tried several method my query is api/v1/Users?query={ loc: { $geoWithin: { $centerSphere: [[38.785834, -121.406417], 10/3963.2 ]} }}

**Comment by candoucreative** [comment]
Finally fixed the issue here is the query that is used to get object near my coordinate. 

Users?query={"gender": "' + gender + '", "age":{"$lte": ' + age + '},  "_id":{"$nin":["579bcdb48441e6e461d99e2b"]}, "loc.coordinates": {"$near": { "$geometry": { "type": "Point",  "coordinates": [' + coordinates + ']},"$maxDistance":' + maxDistance + '}}}'

1. creat an index  {
    "loc.coordinates" : "2dsphere"
}
2. "loc.coordinates": {
        "$near": {
          "$geometry": {
            "type": "Point",
            "coordinates": [38.785834, -121.406417]
          },
          "$maxDistance": 100
        }
    }

hope this will help someone with the same issue.

**Comment by Zertz** [comment]
Thank you, I'm glad you managed to fix it!
