### ISSUE TITLE
Add an internal API

### ISSUE THREAD

**Issue by fdelayen** [florianholzapfel/express-restify-mongoose#305]
It would be great if we could use restify outside express and any real request.

Use case example :
- Create a model and use access and context filter middleware to add security.
- To achieve a complex and secured logic, we need to create an express route outside of express-restify-mongoose but we then cannot use all the security we defined first to get objects.

I'm searching for something like : restify.get('ObjectName', { fields... }) that would act like a real request but returning the result in the code instead of giving it to express.

Is there any way or plan for it ? I can help if needed.

**Comment by Zertz** [comment]
Interesting idea! Decoupling is something that has been worked on, but to allow something like you describe, additional work needs to be done to be able to take out filtering and querying.

I'm going to try and take some time this weekend to triage some issues and come up with a more complete answer for you.

**Comment by fdelayen** [comment]
Thank you very much for your quick answer !
Anyway, we love using express-restify-mongoose :smiley: 
Before moving to node, we had quite the same thing in php, but coupling node, mongoose, angular2 and this rest api gives us an amazing base project ! :grinning:

**Comment by Zertz** [comment]
Thanks for the kind words, sir! I've just started a new job and summer weather is still nice up here so progress has been slow lately, but I have not given up on this just yet :-)

**Comment by fdelayen** [comment]
Haha, I understand that ! It's the same here !
As I'm searching for something to contribute to and I'm using this on multiple projects now (part of my job and private ones), I may help you with issues soon 😀

**Comment by scyrizales** [comment]
I love this idea... i would love to use my postCreate as triggers for my app :)

**Comment by Zertz** [comment]
Most of the complexity in implementing this comes from `operations.js` which couples the request to the querying. If I'm not mistaken, everything else is decoupled so there shouldn't be too many changes outside this file.

As a note to myself and whoever might be interested in picking this up, the general idea here would be to create a module for every function in that file. ie.: `src/operations/getItems.js`

```js
module.exports = function getItems (options) {
  // Code from the current function, return a Promise if possible
}
```

And then, in `operations.js`, the `getItems` function would become:

```js
const getItems = require('./operations/getItems.js')

function getItems (req, res, next) {
  getItems({
    queryOptions:  req._ermQueryOptions,
    ...
  }).then((result) => {
    req.erm.result = items
    next()
  })
}
```

This is rough around the edges (and then some), but it would allow us to expose an API to the app, whether it's based on Express or any other framework.

**Comment by b-gran** [comment]
Just wanted to let you know I'm tackling this issue. Still in a pretty early stage but I'd like to know your thoughts

See https://github.com/b-gran/express-restify-mongoose

Specifically the `issue-305` branch
https://github.com/b-gran/express-restify-mongoose/tree/issue-305

**Comment by Zertz** [comment]
Hey, would you mind creating a PR? It makes it easier to see the diff :-)

**Comment by b-gran** [comment]
Sure, see #314

**Comment by Zertz** [comment]
This is unlikely to be worked on.
