### ISSUE TITLE
populate in serve()

### ISSUE THREAD

**Issue by shaozi** [florianholzapfel/express-restify-mongoose#306]
Hi,
Is there a way to always populate a (or multiple) path in serve call? Ideally: 

```
restify.serve(router, Document, {populate:"path"})

```

I tried to use this:

```
restify.serve(router, Document, {postRead: function (req, res, next) {
    req.erm.result.populate('path').execPopulate().then((result) => {
      // req.erm.result is now fully populated
      next()
    }).catch(next)
  }
})

```

But it error out complaining `TypeError: req.erm.result.populate is not a function`

**Comment by Zertz** [comment]
Make sure to set `lean: false` so that result is a mongoose document. This should allow populate to work expected. Let me know if that works for you!

**Comment by shaozi** [comment]
I tried on two of my collections. The `{populate:"path"}` seems not working at all. Probably is not designed to work in that way? The second `postRead` method works in the first collections. However, it gives this error on the second collection:

```
req.erm.result.populate is not a function
```

**Comment by Zertz** [comment]
`populate` is a mongoose feature, so we need to make sure `req.erm.result` is a mongoose document and not just a plain object. Here's their [documentation](http://mongoosejs.com/docs/api.html#document_Document-populate). On our side, this should work:

```
restify.serve(router, Model, {
  lean: false,
  postRead: function (req, res, next) {
    req.erm.result.populate('path').execPopulate().then((result) => {
      // req.erm.result is now fully populated
      next()
    }).catch(next)
  }
})
```

**Comment by shaozi** [comment]
I may have done something wrong or this is not working. I have created a reproduce repository at 

https://github.com/shaozi/express-restify-mongoose-bug.git

Do you mind to take a look? It is very easy to reproduce on my side.

**Comment by shaozi** [comment]
Ok. The reason for the error is that `req.erm.result` could be of two types: a mongoose document, or an array of mongoose documents. You can do `populate` on a document but cannot on the array.
This makes `postRead` complicated.

**Comment by Zertz** [comment]
While it is [documented](https://florianholzapfel.github.io/express-restify-mongoose/#postread), you make a great point. It is indeed weird that `result` can be of multiple types, documentation could be improved and perhaps split the methods in a future version.
