### ISSUE TITLE
Difference between private and protected - Access types.

### ISSUE THREAD

**Issue by peek4y** [florianholzapfel/express-restify-mongoose#307]
What's the major difference between private and protected access types?

Whenever, I set a property's access to 'private' or 'protected', it always throws an "path is required" error.

Is there no access property, that let's you write, but while reading its 'private' ?

**Comment by Zertz** [comment]
Unfortunately, read-only fields is not something that is natively supported at the moment. However, out is possible to implement using `pre` middleware. I'll dig into sooner of my coffeer and find you an example.

**Comment by Zertz** [comment]
Closing for now, please have a look at #299
