### ISSUE TITLE
How to use other content-types (application/multipart) ?

### ISSUE THREAD

**Issue by OliverFischer** [florianholzapfel/express-restify-mongoose#308]
Hi all, 

I have a path /api/v1/Message generated with erm. Now I want to upload files to a path /api/v1/Message/upload using method post. It seems to be that erm greedy consumes all .../Message paths. I can publish the upload functionality by another path not concurring with erm, but is there maybe another approach to achieve the desired path /api/v1/Message/upload ?

Thanks in advance

Olli

**Comment by Zertz** [comment]
You could set up that path first,

```js
router.post('/api/v1/Message/upload', uploadHandler)

erm.serve(router, Message, options)
```

**Comment by OliverFischer** [comment]
Thx! ;-)
