### ISSUE TITLE
Is there a way to query records that contain a portion of the _id

### ISSUE THREAD

**Issue by Quixomatic** [florianholzapfel/express-restify-mongoose#313]
So if the id of a record is `5760680f87d4a5d8074e1597`

Can we do something like `?query={"_id":">=57"}` ?
Currently this throws an error:

```
{
"message": "Cast to ObjectId failed for value \"57\" at path \"_id\"",
"name": "CastError",
"kind": "ObjectId",
"value": "57",
"path": "_id"
}
```

I know that string fields seem to work fine like when field `table_name` is `sp_quiz`

You could do something like `?query={"table_name":">=sp_"}`

**Comment by Zertz** [comment]
ObjectId's are not a string and cannot be queried like that. However, you can sort by _id and combine that with skip and limit to get documents in the order they were inserted. This isn't entirely true in the case of a sharded cluster and perhaps other setups, but it should work in most cases.

**Comment by Quixomatic** [comment]
Thanks for the heads up. I want to be able to query by unique id so what I'm going to do is use npm shortid to give a unique string id to each record so that it can be searched in the way I'm looking for.

**Comment by Zertz** [comment]
It might be easier for you to save a stringified ObjectId in another field instead. This way you only have a single id to maintain and both can be inferred from one another.

**Comment by Quixomatic** [comment]
Yeah you're right it is much easier to maintain if both the id string field and _id objectid field match up exactly. Good advice again! 👍
