### ISSUE TITLE
koa2 support

### ISSUE THREAD

**Issue by jpravetz** [florianholzapfel/express-restify-mongoose#329]
See issue #226 
koa-restify-mongoose does not support koa2. I am working on a fork of koa-restify-mongoose at https://github.com/jpravetz/koa-restify-mongoose. I've contacted LucianoGanga, but he hasn't responded. His fork did not have unit tests working. I am working on updating the express-restify-mongoose unit tests to work with koa2. There are sufficient changes that I may publish as koa2-restify-mongoose once it's polished enough. Comments or suggestions welcome.

**Comment by Zertz** [comment]
As long as the integration is seamless, I am open to including koa support.

**Comment by jpravetz** [comment]
Express and koa2 support are incompatible and will need it's own repo I believe. I don't see a way to keep them in sync. I want to make sure I am doing the right thing by the community by creating a new repo, and that I am not working cross purposes with anyone else.

**Comment by Zertz** [comment]
I think you are correct, indeed. I would love the core functionality to be decoupled from the frameworks we choose to support but, to be honest, I unfortunately don't have enough spare time to invest anymore.

**Comment by jpravetz** [comment]
That is an interesting point, about keeping the core functionality separate. I'll ponder this as I go along, but of course have a day job too :-) I think it's unlikely to be worth it in this case though.

**Comment by b-gran** [comment]
I've put a decent amount of work into such a decoupling in #314. Started a new job recently so haven't had time to finish it, but plan to ramp back up in the next couple of weeks.

The architecture of that branch works by immutably updating ERM state each time a middleware is called. It should be possible to just drop it in to koa once complete.

**Comment by Zertz** [comment]
I somehow momentarily forgot about the great work @b-gran has put toward this idea.

If we only have to maintain a thin layer to support other frameworks, I wouldn't mind having glue code in this repo and peer dependencies on express/restify/koa so users only have to opt-in to their framework of choice.

**Comment by jpravetz** [comment]
I'm looking at your @b-gran fork and can see potential. I'm trying to think thru (ctx,next) vs (req,res,next), managing state within the middleware (koa should use ctx.state.erm), and return values (koa returns next() which is a promise). Maybe there's just a koa folder for koa middleware, and all the common functionality is split out. I haven't looked at the unit tests yet and if those can be abstracted in any way. Thanks guys for the leads.

**Comment by b-gran** [comment]
The easiest way to integrate with koa is to start with `ERMOperation` (https://github.com/b-gran/express-restify-mongoose/blob/issue-305/src/ERMOperation.js).

All you have to do is come up with some way to set the `ERMOperation` fields using koa middleware. The Express implementation isn't really important -- you can use whatever method you want, as long as the fields get set.
Then, one of the database operations (https://github.com/b-gran/express-restify-mongoose/tree/issue-305/src/api/db) gets called, followed by an output function.
The database op is completely decoupled from a web framework.
The output function will need to be framework-specific, so you'll need to write a koa middleware that takes a fully populated `ERMOperation` and sends it to the client as JSON.

**Comment by jpravetz** [comment]
Happily ERMOperation is what I found to be the starting point too :-). I'd have to modify express-restify-mongoose in minor ways:
- the app.use of merging EROMOperation
- do get/post/put/... on an object that can be either the app (express) or a router (passed in for koa) [I think I need to do this, but will confirm when I re-immerse myself in routing]
It's also nice just to have an errorHandler as the first middleware, that handles Promise.reject() and outputs the error, rather than use onError. So I think a new koa folder with duplicate middleware might be best.

**Comment by jpravetz** [comment]
Okay, I agree that @b-gran's fork is the way forward. I've [checked in my changes here](https://github.com/jpravetz/express-restify-mongoose/tree/issue-329), with a new koa subfolder for koa middleware. No PR yet - I can generate one if it makes diff easier, but it's not ready yet of course. 

There's a top level ```option.koa {boolean}``` to control if it's koa. This maybe should be called ```option.framework = express | koa2```. 

I haven't tackled or gotten my head around the transformations for the api/* yet. But if @b-gran wants to review what's there and make suggestions, that would of course be most welcome. Not sure what my schedule will be to complete this yet.

**Comment by b-gran** [comment]
Hey @jpravetz thanks for all the work you've done over in https://github.com/jpravetz/express-restify-mongoose/tree/issue-329 -- I left a few comments over there.

It might be helpful to create PR against https://github.com/b-gran/express-restify-mongoose/tree/issue-305 so we can track changes and discuss in one place

**Comment by Zertz** [comment]
Glad you guys are working things out! Let me know if you need anything :)

**Comment by jpravetz** [comment]
Update. The [koa2 work is done](https://github.com/jpravetz/express-restify-mongoose/tree/issue-329), unit and integration tests are working. All that remains is to verify the work in a real project, which is delayed somewhat by other Real World interruptions, plus koa routing issues that have caused me to waffle between using [koa-router](https://github.com/alexmingoia/koa-router) and [koa-better-router](https://github.com/tunnckoCore/koa-better-router).

**Comment by SwenChan** [comment]
Hey @jpravetz  thanks for your work, I'm looking for this package now, and how can I use your version for in my koa2 project?Because I can't find your package in npm = ) .

**Comment by jpravetz** [comment]
It's not in npm yet.
It's blocked on a dependent fix to koa-router
<https://github.com/alexmingoia/koa-router/pull/345> that has not been
merged yet,
then an integration (PR) to b-gran's branch
<https://github.com/b-gran/express-restify-mongoose/pull/1>.
In the meantime, you'd have to directly use my fork/branch. The unit tests
were all running, and it looked to be working in a functional system. Alas,
I've been pulled off to work on other stuff, so I'm not sure I'll be
banging on this myself.

It was a lot of work to do this, so I hope it gets adopted.

**Comment by Zertz** [comment]
I wish I could help but time is a bit limited and I don't have any knowledge of koa, if someone is willing to wrap this up I'd be happy to accept a PR!
