### ISSUE TITLE
Warning when trying to sort by a field without index

### ISSUE THREAD

**Issue by vincenting** [florianholzapfel/express-restify-mongoose#330]
Hi, it's easy to forget to create some necessary indexes in collection. But it will cause some serious performance bottleneck when there are hundreds of thousands records in this collection. Recently I got a timeout error and I spent hours to fix it because of my carelessness. 

I think it will be nice to show some warnings when sorting collection with a filed, which has no index created in mongo.

**Comment by Zertz** [comment]
Agreed, it's easy to forget about indexes, which can lead to issues as you scale up. While this is unfortunately out of scope of this library, you can use MongoDB's `explain` method to profile your queries.
