### ISSUE TITLE
can  modify query in Middleware

### ISSUE THREAD

**Issue by Arfius** [florianholzapfel/express-restify-mongoose#331]
Hi,
i'm trying to add some parameter to the url to refine my query.
For Example,in client, Im calling the url 
`/members?query={"country":"Italy"}
`
and
I would to add in the preMiddleware server-side an exception like
`/members?query={$and:[{"country":"Italy"},{"city":"Milan"}]}`

in my preMiddleware, I replace the req.url with new one, but it does not work.
The server perfoms always the fist query.
any advice?

Thanks

**Comment by Zertz** [comment]
You can use [`contextFilter`](https://florianholzapfel.github.io/express-restify-mongoose/#contextfilter)

```js
contextFilter: function (model, req, done) {
  const { query } = req._ermQueryOptions

  if (query && query.country === "Italy") {
    done(model.find({
      city: "Milan"
    }))
  } else {
    done(model.find())
  }
}
```

Let me know if that works for you!

**Comment by Arfius** [comment]
it Works !
Thanks

**Comment by Zertz** [comment]
Good to hear! :)

This particular object is sort of private at the moment, so it will probably be renamed when we decide to expose it, just keep an eye on the changelog in the next major version.

**Comment by Arfius** [comment]
I've a question ( I didn't try the code),
for instance,  if I have a `model Detail `that stores a `objectId` of the` model Order`
and I populate the `Detail` via `GET` ,` i.e. ../detail?populate=order`,
how I can run ( if it is possible) a mixed query for both models?
