### ISSUE TITLE
Allow deep linking of nested schemas

### ISSUE THREAD

**Issue by muliyul** [florianholzapfel/express-restify-mongoose#333]
This is a feature suggestion.
Assume this schema
```javascript
let UserSchema = new Schema({
    firstName: String,
    lastName: {type: String, access: 'private'},
    posts: [{type: Schema.ObjectId, ref: 'Post'}]
});

erm.serve(app, mongoose.model('User', UserSchema, options);
```

Will serve `/user/:id` but what I would fond is to serve also `/user/:id/posts/:id`.

So my suggestion is basically to allow exposing nested schemas. Maybe an options flag?

Edit: the flag could be either a boolean (one level deep) or a specified number.
Edit 2: maybe include a `linkedSchemas` option to select which schemas to be linked. example:

```javascript
erm.serve(app, mongoose.model('User', UserSchema, {
    ...
    linkedSchemas: ['posts']
});
```

**Comment by Zertz** [comment]
The easiest way to achieve that it to instead use [`contextFilter`](https://florianholzapfel.github.io/express-restify-mongoose/#contextfilter) to filter posts by user. The most notable issue with deep routes is that it'll eventually lead to n-depth routes, which is a problem already solved with query parameters and the various built-in hooks.

Let me know if that helps!
