### ISSUE TITLE
postProcess next() for count throws unhandled rejection

### ISSUE THREAD

**Issue by dvlsg** [florianholzapfel/express-restify-mongoose#334]
Node: 7.6.0
ERM: 4.1.3
Mongoose: 4.9.1
Express: 4.15.2

Issue (possibly): Using a restify default postProcess which calls `next()` results in an unhandled rejection when loading a `GET /count` endpoint.

Was unsure if this was intended behavior / that you shouldn't actually call `next()` in postProcess? I know it's intended as a sort of spin-off process for logging and such (according to docs, anyways), and not _really_ part of the middleware chains.

Reproduce: 

```js
const express = require('express');
const bodyParser = require('body-parser');
const methodOverride = require('method-override');
const mongoose = require('mongoose');
const restify = require('express-restify-mongoose');
const app = express();
const router = express.Router();

app.use(bodyParser.json());
app.use(methodOverride());

mongoose.connect('mongodb://localhost:27017/database');

function postProcess(req, res, next) {
  return next();
}

const restifyDefaultOptions = {
  postProcess,
};

restify.defaults(restifyDefaultOptions);

restify.serve(
  router,
  mongoose.model(
    'Customer',
    new mongoose.Schema({
      name: { type: String, required: true },
      comment: { type: String },
    })
  )
);

app.use(router);

app.listen(3000, () => {
  console.log('Express server listening on port 3000');
});
```

* Start the server as above and `GET localhost:3000/api/v1/Customer/count`
* Response should still make it back to the browser / curl / whatever just fine, but the server shows this:
  * `Unhandled rejection Error: Can't set headers after they are sent.`

**Comment by Zertz** [comment]
Yeah, since the response has already been sent at that point, this is the expected behavior. However, you made me notice `next` shouldn't be mentioned in the docs or even passed to `postProcess`.
