### ISSUE TITLE
prepareOutput middleware does not call next

### ISSUE THREAD

**Issue by sgilroy** [florianholzapfel/express-restify-mongoose#337]
When experess-restify-mongoose is used and the restify server has any middleware (via `server.use()`) or a listener attached to the `after` event (http://mcavage.me/node-restify/#request-api), the middleware and listener will not get called. To fix this, the `next()` callback should be called at the end of the `prepareOutput` middleware.

Workaround: specify the `postProcess` option, as in `postProcess: (req, res, next) => next()`

**Comment by Zertz** [comment]
Which restify version are you using?

**Comment by bamidei** [comment]
I have just reviewed the current state of this issue and it still does exist even with the latest (v5) code base.  To answer the previous question, we are currently using restify v4.0.3.

Please consider merging the above-cited PR to resolve the issue.
