### ISSUE TITLE
url query does not reflect mongoose query --- wrong result

### ISSUE THREAD

**Issue by slokmanex** [florianholzapfel/express-restify-mongoose#342]
Hi, 
I set up the rest-api every thing works fine.  But, I was supersized that the api was returning  zero counts for my collection. When enabled mongoose debug I noticed that mongoose is calling different collection ( appended "s" to collection name), this does not happen when the collection name ends with a number. 

 When I use **: http://localhost:3000/api/v1/test/count** 
[nodemon] starting `node .\app.js`
Express server listening on port 3000
Connected to database mongodb://10.4.202.237/cvm
**Mongoose: tests.count({}, {})**

When I use : **http://localhost:3000/api/v1/test2/count** 
[nodemon] restarting due to changes...
[nodemon] starting `node .\app.js`
Express server listening on port 3000
Connected to database mongodb://10.4.202.237/cvm
**Mongoose: test2.count({}, {})**

**Comment by Zertz** [comment]
mongoose pluralizes collection names, it can be disabled by specifying a collection name:

`const Model = mongoose.model('Model', schema, collectionName);`
