### ISSUE TITLE
versionKey

### ISSUE THREAD

**Issue by bellomimarc** [florianholzapfel/express-restify-mongoose#343]
Hi,
the versionKey of my schema does not update.
This is my schema 
`new mongoose.Schema(
    {
        city: { type: String, required: true },
        timezone: { type: String, required: true },
    }
);`
I create an order through "http post" and then update it through "http put" but the field __v is equal to zero.

How can i configure express-restify-mongoose to update versionKey?

Thanks a lot,
Marcello

**Comment by Zertz** [comment]
As far as I know, this should be handled by mongoose.
