### ISSUE TITLE
Feature request: add 'select' option for serve function

### ISSUE THREAD

**Issue by bitstrider** [florianholzapfel/express-restify-mongoose#353]
Hey it would be great to utilize [`Query#select`](http://mongoosejs.com/docs/api.html#query_Query-select) like such: 

```javascript
serve(router,userModel,{select:'name email'}) 
// creates routes that will return user objects with only the fields name, email (and _id by default)
```

PR worthy?

**Comment by Zertz** [comment]
Duplicate of #299 but definitely something worth looking into! I think `select` gets even more interesting if you can set it at the request level, would it work for you at a simple option?
