### ISSUE TITLE
An apparently valid query returns invalid_json_query

### ISSUE THREAD

**Issue by grochadc** [florianholzapfel/express-restify-mongoose#382]
I have used this query on mongo shell:
`{“_id”: {“$gt”: ObjectId(‘5b...’)}}`

and it returns the expected documents. But when I try mongoose by using `?query=` I get `invalid_json_query`

What am I doing wrong?

**Comment by Zertz** [comment]
`ObjectId` is not JSON serializable, you must take it out of the query:

```
{"_id": {"$gt": "5b...")}}
```
