### ISSUE TITLE
Boolean support

### ISSUE THREAD

**Issue by 6eDesign** [florianholzapfel/express-restify-mongoose#39]
Is there boolean support for query parameters? (for values stored as boolean: true/false instead of string: 'true'/'false')  And if not, should we add some sort of support?  I'm not sure if it would be best to create a new key like was done for regex expressions (=~), maybe ==, or alternatively, we could use a keyword for True/False or even automatically convert any incoming value to it's boolean equivalent. 

Have you encountered the need for this yourself?

**Comment by lioralpha** [comment]
Querying with boolean property is not working checked on version 3.2.0.
Example : 
{"name":{"$regex":"/.*shirt.*/","$options":"i"},"status":":1}

**Comment by Zertz** [comment]
It seems like there might be a typo in your query:

```js
{
  "name": {
    "$regex": "/.*shirt.*/",
    "$options":"i"
  },
  "status": ":1
}
```

Should be:

```js
{
  "name": {
    "$regex": "/.*shirt.*/",
    "$options":"i"
  },
  "status": true
}
```

Also, you can use `"/.*shirt.*/i"`instead of `$options`.
