### ISSUE TITLE
collection.count is deprecated

### ISSUE THREAD

**Issue by wottpal** [florianholzapfel/express-restify-mongoose#390]
I get the following warning when doing a `count` get request on a model:

```
(node:36515) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead
```

**Comment by wottpal** [comment]
Another warning:

```
(node:36991) DeprecationWarning: collection.findAndModify is deprecated. Use findOneAndUpdate, findOneAndReplace or findOneAndDelete instead.
```

**Comment by wottpal** [comment]
I guess it's because I'm on `mongoose@^5.3.14` and the required version is `mongoose@^4.0.0` 🤦‍♂️ My fault.

@florianholzapfel But will this repository maintained in the future, is it save to start building an application with it right now? Despite a bunch of depreciation warnings everything seems to work fine right now.

Grüße aus Jena

**Comment by MidnightP** [comment]
+1

@wottpal me and my colleagues extensively rely on this library -- at least 12 services and counting. We will seriously consider systematic contribution when required from our side.

I didn't see signs of life here in a while and collaboration is very much preferred over forking...
