### ISSUE TITLE
Contribute to this repository

### ISSUE THREAD

**Issue by pimvanderheijden** [florianholzapfel/express-restify-mongoose#391]
Hello @florianholzapfel and anyone reading this.

We (ViriCiti) would love to contribute to this project before serious compatibility issues with Mongoose arise.

Any idea about the future of this repository?

Can we be part of it?

Collaboration is highly much preferred over forking...

**Comment by Zertz** [comment]
Hello, thanks for the support! I'm currently at work but I'll invest some time by the weekend.

Do you have any particular issues in mind?

**Comment by MidnightP** [comment]
this one for example: https://github.com/florianholzapfel/express-restify-mongoose/pull/386

Another one is:

It seems that either 1) there is something wrong with Mongoose v5 `Model.pre("save", () => {})` hooks or 2) we need better documentation / explanation of the relation between Mongoose hooks and the "pre" and "post" hooks of this project.

**Comment by hereischris** [comment]
@Zertz @MidnightP hi there!
any update on the status of this project? we would also be interested in reviving it.

**Comment by MidnightP** [comment]
Not that I know of. We're definitely still interested in a revival.

What kind of features / changes were you thinking about?

**Comment by hereischris** [comment]
First of all, mongoose 5 support.

**Comment by MidnightP** [comment]
sound great

we need help from @Zertz to acheive this

**Comment by Zertz** [comment]
Hey folks, thanks for your interest!

PR's are welcome! Try to keep changes small and non breaking and I'll be able to merge and publish swiftly.

I can give write access to the repo if you're interested in contributing.

**Comment by MidnightP** [comment]
Hey Zertz! Thanks for the reply

I would love to contribute, for example by finishing this PR: https://github.com/florianholzapfel/express-restify-mongoose/pull/386
Do you have any idea what's wrong here?

Or allowing upsert on PUT is also very interesting for us: https://github.com/florianholzapfel/express-restify-mongoose/pull/392

Mongoose 5 we also find important but I'm not sure yet about the work that needs to be done in that respect

**Comment by Zertz** [comment]
I think we can land those two PR's in the current version and then release v6 with the only breaking change being the Mongoose upgrade.

**Comment by wottpal** [comment]
Sounds great that this project is becoming alive again :) Mongoose 5 support would be so great.

**Comment by StoyanStAtanasov** [comment]
What is the status? Is this project alive or what? Came here after doing a project with GraphQL - too complex. Wanted something simple. If this project is dead or dying, any alternatives other than GraphQL?

**Comment by Zertz** [comment]
Closing this as we're about to release support for Mongoose 6.
