### ISSUE TITLE
Usage Question: How to use express-restify-mongoose with other package mpath for Mongoose

### ISSUE THREAD

**Issue by mickey58github** [florianholzapfel/express-restify-mongoose#395]
I have put a question about usage of this great package in combination with another Mongoose add-on package, MPath, which is a  schema extension to manage materialized tree structures.

Not having seen this Issues section including questions on github, I raised my question on Stackoverflow (https://stackoverflow.com/questions/57553213/can-mongoose-materialized-path-and-mongoose-restify-be-used-together).

Hope you can read the question there, I don't repeat it here to keep things short. No ansswer yet on SO, so kindly asking whether I can get a quick answer here.

It's probably a pretty basic question, but important. I browsed the docs, but did not find an example on how to add custom methods (as provided by the other package MPath) and their corresponding REST APIs to the CRUD style REST APIs generated by default through express-restify-mongoose. I'm also a bit worried whether the under cover hooks added by the two packages to the schema/model might interfere somehow.

Thanks much for helping me with this!

**Comment by Zertz** [comment]
You've probably figured it by now but here's the answer nonetheless! https://stackoverflow.com/a/62980951/1779688
