### ISSUE TITLE
No typescript definition file in 5.1.0

### ISSUE THREAD

**Issue by StoyanStAtanasov** [florianholzapfel/express-restify-mongoose#400]
I get an error in my typescript project. 

> error TS7016: Could not find a declaration file for module 'express-restify-mongoose'.

I have the latest package at this time 5.1.0 but there is no type definition file in 
 my `node_modules/express-restify-mongoose`.
Also `npm install -D @types/express-restify-mongoose does` not work. 

> ERR! 404  '@types/express-restify-mongoose@latest' is not in the npm registry.

I see the `index.d.ts` file in the code directory of this repository and if I add it manually to the `node_modules/express-restify-mongoose` folder then everything works.

Please make the type definitions file part of the distribution.

**Comment by Pierre-Demessence** [comment]
Same issue with version 6.0.0

**Comment by botv** [comment]
#409 fixes this issue, the types definition file was not specified in `package.json`.
