### ISSUE TITLE
Can't use $toObjectId in query

### ISSUE THREAD

**Issue by 95deepan** [florianholzapfel/express-restify-mongoose#403]
# Query:

`http://baseurl/api/v1/roles?query={"user": { "$toObjectId":"5decc6d2687f6a419c9ee2bw" }}`

# Response:

```json
{
    "code": 400,
    "message": "Can't use $toObjectId",
    "success": false
}
```

Did I miss anything here?

**Comment by Zertz** [comment]
The message `Can't use $toObjectId` comes from MongoDB itself because [`$toObjectId`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/toObjectId/) is an aggregation operator and can't be used in a `find` query.
