### ISSUE TITLE
Denial of service vulnerability

### ISSUE THREAD

**Issue by earmbrust** [florianholzapfel/express-restify-mongoose#404]
$ npm audit

                       === npm audit security report ===

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  High            Denial of Service

  Package         mongodb

  Patched in      >=3.1.13

  Dependency of   express-restify-mongoose

  Path            express-restify-mongoose > mongoose > mongodb

  More info       https://npmjs.com/advisories/1203

found 1 high severity vulnerability in 49 scanned packages
  1 vulnerability requires manual review. See the full report for details.

**Comment by florianholzapfel** [comment]
1da83bff08c9bb88c849dc1d5bb35dd2a754299d
