### ISSUE TITLE
Compile to dist directory before serving to NPM

### ISSUE THREAD

**Issue by webberwang** [florianholzapfel/express-restify-mongoose#407]
Currently the `package.json` uses the `main` as `./src/express-restify-mongoose`. Subsequent scripts make references to `node_modules` but module resolution for webpack does not resolve to `express-restify-mongoose/node_modules`.

As a library, it should be compiled to dist folder before serving

**Comment by Zertz** [comment]
PR welcome!

**Comment by Zertz** [comment]
Closing this as the library is not meant to be used with webpack and there are many other bundlers with slightly different opinions. If you need to bundle the library, it should be set up within your bundler's configuration.
