### ISSUE TITLE
Why lean is bad for performance?

### ISSUE THREAD

**Issue by wizardnet972** [florianholzapfel/express-restify-mongoose#408]
Why lean is bad for performance?

In the [express-restify-mongoose docs](https://florianholzapfel.github.io/express-restify-mongoose/#lean):

Whether or not mongoose should use .lean() to convert results to plain old JavaScript objects. This is bad for performance, but allows returning virtuals, getters and setters.

But in [mongoose docs](https://mongoosejs.com/docs/tutorials/lean.html):

Faster Mongoose Queries With Lean
The lean option tells Mongoose to skip hydrating the result documents. This makes queries faster and less memory intensive, but the result documents are plain old JavaScript objects (POJOs), not Mongoose documents.

**Comment by Zertz** [comment]
I agree, the wording on our end is confusing here! We meant to say setting this option to `false` is bad for performance. Would you mind submitting a PR to the docs?
