### ISSUE TITLE
conflicting mongoose versions in package.json

### ISSUE THREAD

**Issue by kswedberg** [florianholzapfel/express-restify-mongoose#412]
The package.json file has conflicting mongoose versions listed in `dependencies` (`"^5.8.10"`)and `peerDependencies` (`"^4.0.0"`). This is resulting in the following error:

```bash
npm ERR! peer dep missing: mongoose@^4.0.0, required by express-restify-mongoose@6.0.0
```

History: 
* Mongoose was moved from `dependencies` to `peerDependencies` back in October 2015 (7910bc8fb3503c32306c7d0c09b67128956a1373), and that line hasn't been changed since then.
* It was then added again to `dependencies` in November 2019 (a7f079abe4e4c91c14a2bf6c78d7bd2fd1275187)
* From then on, only the version in `dependencies` was updated.

I'm not sure how you want to approach this, but either the `peerDependencies` version should be updated and the line `dependencies` removed or the `peerDependencies` line should be removed.

I'd be happy to submit a PR if that would make things easier for you; just let me know which approach you'd like to take.

Thanks!

**Comment by Zertz** [comment]
I feel like it should only be a peer dependency but perhaps @florianholzapfel can chime in?

**Comment by florianholzapfel** [comment]
I also feel like `peerDependencies` is the way to go

**Comment by kswedberg** [comment]
That's what I was thinking, too. @florianholzapfel , it's a pretty quick fix. Do you want to do it, or would you like me to submit a PR?

**Comment by florianholzapfel** [comment]
i will provide a fix. thank you for raising this issue!

**Comment by kswedberg** [comment]
You're welcome! And thanks for the quick reply.
