### ISSUE TITLE
TypeScript definitions file not in NPM package

### ISSUE THREAD

**Issue by zb140** [florianholzapfel/express-restify-mongoose#414]
For some reason, it appears that the TypeScript definitions file `index.d.ts` is not included in the published NPM package.  I verified this for version 6.1.2 and 6.1.1 by manually downloading the tarball from `npmjs.org`.  Manually downloading the file from github and placing it in the correct location in `node_modules` works as expected.

**Comment by Zertz** [comment]
Indeed, `index.d.ts` is not included in the `files` array in [package.json](https://github.com/florianholzapfel/express-restify-mongoose/blob/master/package.json#L80)

Can you submit a PR?

**Comment by zb140** [comment]
Sure, I won't be able to get to it tonight but I'll be happy to do it tomorrow.

**Comment by zb140** [comment]
This was fixed a while back in #415.  Thanks!
