### ISSUE TITLE
Tests are broken when running mongo 4.4 and node 14.15.0 ?!

### ISSUE THREAD

**Issue by OliverFischer** [florianholzapfel/express-restify-mongoose#418]
Hi all, 

simple question : I tried to run the tests against a mongo 4.4 with mongoose 5.9.24. I experience some strange test fails, mostly string comparisons like undefined === 'undefined' false, but also mongo errors telling me that `errors.errMsg` does not exist any more as well as the test case `POST Invoice 400` in create.js where the body contains a json which is different concerning the returned properties:
```{
        "errors": {
                "customer": {
                        "stringValue": "\"invalid-id\"",
                        "kind": "ObjectId",
                        "value": "invalid-id",
                        "path": "customer",
                        "name": "CastError",
                        "message": "Cast to ObjectId failed for value \"invalid-id\" at path \"customer\""
                },
                "products.0": {
                        "stringValue": "\"invalid-id\"",
                        "kind": "ObjectId",
                        "value": "invalid-id",
                        "path": "products.0",
                        "$originalErrorPath": "products",
                        "name": "CastError",
                        "message": "Cast to ObjectId failed for value \"invalid-id\" at path \"products\""
                },
                "products": {
                        "stringValue": "\"[ 'invalid-id', 'invalid-id' ]\"",
                        "kind": "Array",
                        "value": [
                                "invalid-id",
                                "invalid-id"
                        ],
                        "path": "products",
                        "name": "CastError",
                        "message": "Cast to Array failed for value \"[ 'invalid-id', 'invalid-id' ]\" at path \"products\""
                }
        },
        "_message": "Invoice validation failed",
        "name": "ValidationError"
}
```
with the products.0 section not mentioned in the expectation. BTW, this tests also fails always on the string pattern matching of `invalid-id`. 

I'm on mac os x catalina running node in `v14.15.0`. Seems like I have completely overlooked something simple. May be anyone of you can point me to the right direction ?

**Comment by Zertz** [comment]
It's probably not you! These tests have always been perhaps a bit too strict. Those error messages tend to change when MongoDB is upgraded so they'll break unexpectedly.

When running tests locally, don't worry about these failures. Once a PR is opened and they run on CI, they *should* pass.

**Comment by OliverFischer** [comment]
ok, thanks for the info. I modified the failing tests to match the expectations and only skipped the invoice test.
