### ISSUE TITLE
Dynamic model Enhancement for mutli-tenancy

### ISSUE THREAD

**Issue by OliverFischer** [florianholzapfel/express-restify-mongoose#419]
To provide dynamic resolving of custom models to enable multi-tenancy applications to work with different models , erm has a feature to resolve a dynamic model by providing a `modelFactory#getModel` method. This method is implemented as a middleware in this way in express-restify-mongoose.js: 
```
  app.use((req, res, next) => {
    const getModel = options.modelFactory && options.modelFactory.getModel

    req.erm = {
      model: typeof getModel === 'function' ? getModel() : model,
    }

    next()
  })
```
I like to resolve a custom model by inspecting the informations in the request headers and url when entering express:

1. GET /tenant1/customer
2. GET /tenant2/customer

To provide a method able to return for tenant1 a different model from tenant2, it would be great if the implementation of `getModel()` can be changed to `getModel(req)` to enable an implementation of `getModel(req)` returning a custom model based on the informations passed in the request. 

Is that possible and should I provide a PR for that?

**Comment by Zertz** [comment]
I'm not familiar with this bit of code but I would tend to agree that passing `req` would be useful.

Feel free to open a PR!

**Comment by OliverFischer** [comment]
Thx for accepting.
