### ISSUE TITLE
Configurable mongo address

### ISSUE THREAD

**Issue by OliverFischer** [florianholzapfel/express-restify-mongoose#421]
Hi,

do you think it is possible to take the mongo url either from the preconfigured string or from an environment variable. Change would be simple `mongoose.connect(process.env.MONGODB_ADDRESS || 'mongodb://localhost/database')`. It would enable a developer to use a connection containing url credentials or connecting to a replicaSet on a cluster. If no env var is provided, it can simply fail back to the localhost address.

**Comment by Zertz** [comment]
Do you mean when running tests?

**Comment by OliverFischer** [comment]
Yes, perhaps it is not the normal development flow, but we ran our tests against a "downsized" version of our kubernetes cluster as a set of containers running with docker-compose. So components like mongodb running in these containers are at least running with "mongodb://user:pass@localhost/somedb?authSource=admin". I do not know if this is a rare case, but for now, i am always modifying the url to make it suitable for our needs.

**Comment by Zertz** [comment]
From a quick search, `MONGO_URL` seems to be a somewhat common name for this.

You can go ahead and create a PR, I'll publish a release after!

**Comment by OliverFischer** [comment]
Thx.
