### ISSUE TITLE
Sorting doc error

### ISSUE THREAD

**Issue by StoyanStAtanasov** [florianholzapfel/express-restify-mongoose#436]
⚠️Warning : The [Docs](https://florianholzapfel.github.io/express-restify-mongoose/) are wrong about how to use sort. Use with 1(acsending), -1(descending) instead with 1,0
![image](https://user-images.githubusercontent.com/49271294/183919171-a1e8ddc2-cf2b-4a4f-8e45-c8fce0696d25.png)

**Comment by Zertz** [comment]
I can't find a mention to 1/0 being ascending or descending in the [sort documentation](https://florianholzapfel.github.io/express-restify-mongoose/#sort), can you point to the exact place where you're seeing this mistake?

**Comment by StoyanStAtanasov** [comment]
Thanks for responding so quick! I thought that the project is not maintained :)

In the "Querying" paragraph. I have updated the first post with a photo.

**Comment by StoyanStAtanasov** [comment]
Made a pull request #437

**Comment by Zertz** [comment]
Oh, my bad, I misread the issue!
