### ISSUE TITLE
Feature request: populate field do not work with POST & PUT requests

### ISSUE THREAD

**Issue by syzer** [florianholzapfel/express-restify-mongoose#52]
Currently cannot use "?populate=filed", when POST, or PUT, objects to express-restify-mongoose.

It works only for GET requests

**Comment by arathael** [comment]
Plans on implementing this? Can I help?

**Comment by syzer** [comment]
would be not sufficient to return 200?

**Comment by Zertz** [comment]
@arathael This should be easy now. Basically you want to add the prepareQuery midfleware to POST/PUT methods and run model.populate with req._ermQueryOptions.populate after  creating/saving the document.

**Comment by arathael** [comment]
Niice job!

**Comment by Zertz** [comment]
Not implemented, just some pointers :)
