### ISSUE TITLE
Query on virtual fields

### ISSUE THREAD

**Issue by maafy6** [florianholzapfel/express-restify-mongoose#61]
Would it be possible to add the ability to query a virtual field? It looks like it currently only queries on the fields in the schema.

**Comment by fairsayan** [comment]
+1

**Comment by chiefGui** [comment]
+1

**Comment by Zertz** [comment]
Sorry guys, this is actually impossible.

> Virtuals are NOT available for document queries or field selection. Only non-virtual properties work for queries and field selections.

https://futurestud.io/blog/understanding-virtuals-in-mongoose/
