### ISSUE TITLE
Suggestion: public fields

### ISSUE THREAD

**Issue by Zertz** [florianholzapfel/express-restify-mongoose#63]
Currently, it is possible to blacklist fields using the `private` and `protected` options. However, blacklisting is dangerous because if a sensitive field is added into the model and the list of private fields isn't updated accordingly, it will leak.

My suggestion is to add a `public` fields option which would instead allow whitelisting.

``` javascript
public: '_id,firstname,lastname'
```

This way, queries would return those three fields and if I add `ssn` to that model, it will not be returned.

Also, conflicts between `public` and `private` or `protected` should always favor the latter. For example, the following options would return `_id` and `firstname`, but not `lastname`.

``` javascript
public: '_id,firstname,lastname',
private: 'lastname'
```

Thoughts?

**Comment by ErikEvenson** [comment]
This is a nice solution, but ERM will still send the _id field if it is not blacklisted.
