### ISSUE TITLE
Adding to sub(sub) documents

### ISSUE THREAD

**Issue by mwkrieger** [florianholzapfel/express-restify-mongoose#81]
Hi there. 

After a few days of reading and searching, I'm not sure I can do what I want to do with this module. As a last ditch effort, I thought I would reach out and see if there were any wise words from people much smarter than me. 

I have a schema called Locale. This schema has a subdocument defined one level below the root - called brands. Under that schema, I have another sub document (a sub-sub?) schema defined as variants. Basically every locale can have multiple brands. Those brands can have multiple variants. My model looks like this: 

```
var Locale = new Schema({
    name: {
        type: String,
        required: true
    },
    active: Boolean,
    code: {
        type: String,
        required: true
    },
    brands: [{
        masterbrand: {
            type: Schema.Types.ObjectId,
            ref: 'Masterbrand'
        },
        customlocalename: {
            type: String
        },
        active: Boolean,
        variants: [{
            mastervariant: {
                type: Schema.Types.ObjectId,
                ref: 'Mastervariant'
            },
            customlocalename: {
                type: String
            },
            active: Boolean
        }]
    }]
});
```
For the brand, I can put in a new document and sub document in the database using the following PUT to /api/v1/Locales:

```
{
    "name": "US",
    "active": "True",
    "code": "EN-US",
    "brands": [{
        "masterbrand": "5462811e6186885ee60ed941",
        "customlocalename": "Custom name 1",
        "active": "True",
        "variants": [{
            "mastervariant": "546281b76186885ee60ed942",
            "customlocalename": "Custom variant 1"
        }]
    }]
}
```
Which results in: 

```
{
    "__v": 0,
    "name": "US",
    "active": true,
    "code": "EN-US",
    "_id": "5464befe47a5dcc843008fdf",
    "brands": [{
        "masterbrand": "5462811e6186885ee60ed941",
        "customlocalename": "Custom brand name 1",
        "active": true,
        "_id": "5464befe47a5dcc843008fe0",
        "variants": [{
            "mastervariant": "546281b76186885ee60ed942",
            "customlocalename": "Custom variant name 1",
            "_id": "5464befe47a5dcc843008fe1"
        }]
    }]
}
```
Now here's where I get stuck. If I want to add another brand to the brand subdocument, I thought I could PUT the new brand in like this: 
```
/api/v1/Locales/5464befe47a5dcc843008fdf

Json:
{
    "brands": [{
        "masterbrand": "5462811e6186885ee60ed941",
        "customlocalename": "Custom brand name 2",
        "active": "True",
        "variants": [{
            "mastervariant": "546281b76186885ee60ed942",
            "customlocalename": "Custom brand name 2",
            "active": "True"
        }]
    }]
}
```
But when I do this, it overwrites (replaces) the current brand. This is the same for the variants under brand as well. 

I figure I have to do an $upsert, but can't seem to get it right in the call. 

Is there a way with this module that I can add multiple subdocuments to the root AND add multiple subdocuments under that subdocument? 

I'm either doing something really stupid, or the module just isn't meant to do this. 

Any advice?

**Comment by Zertz** [comment]
@florianholzapfel I think this would add too much complexity and magic, what do you think?

**Comment by arathael** [comment]
This would be a great feature indeed. Maybe through a `members` option to create routes for sub collections.

**Comment by MayankDargan** [comment]
what if i need a sub doc in this way that 

i have a schema named department

department: { title:string, dept:[department]}

how this can be done in mongoose?

**Comment by Zertz** [comment]
Closing this in favor of #224
