### ISSUE TITLE
more mongoose query method support

### ISSUE THREAD

**Issue by jupe** [florianholzapfel/express-restify-mongoose#86]
I've developed [library](https://github.com/jupe/mongoose-query), which support also _distinct_, _mapReduce_ and _aggregate_ mongo(ose) features. This library would be more useful if you could add support for those methods as well. At least _distinct_, it is easiest..

**Comment by Zertz** [comment]
While we don't have support for the aggregation framework, everything else works and I feel like this is something that is best left up to the user since it would require a specific endpoint (ie.: `/api/v1/Model/aggregate`) which could potentially collision with a resource id.
