### ISSUE TITLE
POST does not return error reported by asynchronous pre save

### ISSUE THREAD

**Issue by william-poitras** [florianholzapfel/express-restify-mongoose#88]
When a Mongoose model uses async pre save middleware and reports and error with done, the body of the POST response does not include the error.  So for example:
```javascript
schema.pre('save', true, function(err, model, next, done) {
    next();
    asyncDonewithError(done, 'ThisIsMyErrorMessage');
});
```
I can get a Mongoose unit test to return the error message, but when I invoke the REST interface, I only get a status code of 400 (Bad Request) and an empty body.

However, when I trigger simple schema validation (either custom validation function or violating unique constraints) the REST interface returns status code of 400 with the mongoose error detail in the body.

Is there a way to get Mongoose middleware errors to propagate like normal validation errors?

**Comment by florianholzapfel** [comment]
Hi, thank you for the info. I will have a look at it.

**Comment by joe-hilling** [comment]
Anyone know of a workaround for this? I have a single model amongst many that has `.pre('save',..)` validation and I don't want to roll my own web-db routing for the sake of my API communicating validation errors.

**Comment by Zertz** [comment]
What happens when there's an async validation error?

**Comment by Zertz** [comment]
@joe-hilling The fix unfortunately requires a small breaking change and will land in v4.0 soon
