### ISSUE TITLE
[suggestion] deprecate/remove fullErrors and createError

### ISSUE THREAD

**Issue by Zertz** [florianholzapfel/express-restify-mongoose#98]
Since it's now possible for developers to implement a custom error handler, `fullErrors` doesn't need to exist anymore. The default `onError` handler should only return status and a default HTTP message and it should be made obvious to implement a custom handler if you need more than that.

Also, `createError` is currently used inconsistently and its sole reason to exist is `fullErrors` so that should go too in favor of simply setting a status when an error is found. ie: `err.status = 400`

The idea is that developers shouldn't rely on the library to perform logic on the data being pushed to the client, it should be up to the app.

Of course, this would be a breaking change for at least some users so it would be best suited for an eventual 1.0.0 release.

**Comment by Zertz** [comment]
@florianholzapfel Could you create a 1.0.0-dev (or something along those lines!) branch?

I'll work on PR's for this and mongoose 4 (which is also a breaking change for many projects)

**Comment by florianholzapfel** [comment]
@Zertz I have created a 1.0.0-dev branch

**Comment by Zertz** [comment]
See PR #114
